/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthUsersRouteRouteImport } from './routes/_auth/users/route'
import { Route as AuthSpacesIndexRouteImport } from './routes/_auth/spaces/index'
import { Route as AuthSpacesNewRouteImport } from './routes/_auth/spaces/new'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthUsersRouteRoute = AuthUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSpacesIndexRoute = AuthSpacesIndexRouteImport.update({
  id: '/spaces/',
  path: '/spaces/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSpacesNewRoute = AuthSpacesNewRouteImport.update({
  id: '/spaces/new',
  path: '/spaces/new',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/users': typeof AuthUsersRouteRoute
  '/': typeof AuthIndexRoute
  '/spaces/new': typeof AuthSpacesNewRoute
  '/spaces': typeof AuthSpacesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/users': typeof AuthUsersRouteRoute
  '/': typeof AuthIndexRoute
  '/spaces/new': typeof AuthSpacesNewRoute
  '/spaces': typeof AuthSpacesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/users': typeof AuthUsersRouteRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/spaces/new': typeof AuthSpacesNewRoute
  '/_auth/spaces/': typeof AuthSpacesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/users' | '/' | '/spaces/new' | '/spaces'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/users' | '/' | '/spaces/new' | '/spaces'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/users'
    | '/_auth/'
    | '/_auth/spaces/new'
    | '/_auth/spaces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/users': {
      id: '/_auth/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthUsersRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/spaces/': {
      id: '/_auth/spaces/'
      path: '/spaces'
      fullPath: '/spaces'
      preLoaderRoute: typeof AuthSpacesIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/spaces/new': {
      id: '/_auth/spaces/new'
      path: '/spaces/new'
      fullPath: '/spaces/new'
      preLoaderRoute: typeof AuthSpacesNewRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthUsersRouteRoute: typeof AuthUsersRouteRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthSpacesNewRoute: typeof AuthSpacesNewRoute
  AuthSpacesIndexRoute: typeof AuthSpacesIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthUsersRouteRoute: AuthUsersRouteRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthSpacesNewRoute: AuthSpacesNewRoute,
  AuthSpacesIndexRoute: AuthSpacesIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
