/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/root.layout'
import { Route as loginDotpageRouteImport } from './routes/login.page'
import { Route as authDotlayoutRouteImport } from './routes/auth.layout'
import { Route as pendingAttachmentsPageRouteImport } from './routes/pending-attachments/page'
import { Route as indexDotpageRouteImport } from './routes/index.page'
import { Route as usersNewDotpageRouteImport } from './routes/users/new.page'
import { Route as telegramTasksPageRouteImport } from './routes/telegram/tasks/page'
import { Route as telegramMirrorsPageRouteImport } from './routes/telegram/mirrors/page'
import { Route as spacesNewDotpageRouteImport } from './routes/spaces/new.page'
import { Route as spacesImportDotpageRouteImport } from './routes/spaces/import.page'
import { Route as usersIndexPageRouteImport } from './routes/users/index/page'
import { Route as spacesIndexPageRouteImport } from './routes/spaces/index/page'
import { Route as spacesSlugTemplatesPageRouteImport } from './routes/spaces/_slug_/templates/page'
import { Route as spacesSlugSettingsPageRouteImport } from './routes/spaces/_slug_/settings/page'
import { Route as spacesSlugMembersDotpageRouteImport } from './routes/spaces/_slug_/members.page'
import { Route as spacesSlugExportDotpageRouteImport } from './routes/spaces/_slug_/export.page'
import { Route as spacesSlugFiltersNewDotpageRouteImport } from './routes/spaces/_slug_/filters/new.page'
import { Route as spacesSlugFieldsNewDotpageRouteImport } from './routes/spaces/_slug_/fields/new.page'
import { Route as spacesSlugFiltersIndexPageRouteImport } from './routes/spaces/_slug_/filters/index/page'
import { Route as spacesSlugFieldsIndexPageRouteImport } from './routes/spaces/_slug_/fields/index/page'
import { Route as spacesSlugFiltersFilterNameEditDotpageRouteImport } from './routes/spaces/_slug_/filters/_filterName_/edit.page'
import { Route as spacesSlugFieldsFieldNameEditDotpageRouteImport } from './routes/spaces/_slug_/fields/_fieldName_/edit.page'

const loginDotpageRoute = loginDotpageRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authDotlayoutRoute = authDotlayoutRouteImport.update({
  id: '/_auth.layout',
  getParentRoute: () => rootRouteImport,
} as any)
const pendingAttachmentsPageRoute = pendingAttachmentsPageRouteImport.update({
  id: '/pending-attachments',
  path: '/pending-attachments',
  getParentRoute: () => authDotlayoutRoute,
} as any)
const indexDotpageRoute = indexDotpageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authDotlayoutRoute,
} as any)
const usersNewDotpageRoute = usersNewDotpageRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => authDotlayoutRoute,
} as any)
const telegramTasksPageRoute = telegramTasksPageRouteImport.update({
  id: '/telegram/tasks',
  path: '/telegram/tasks',
  getParentRoute: () => authDotlayoutRoute,
} as any)
const telegramMirrorsPageRoute = telegramMirrorsPageRouteImport.update({
  id: '/telegram/mirrors',
  path: '/telegram/mirrors',
  getParentRoute: () => authDotlayoutRoute,
} as any)
const spacesNewDotpageRoute = spacesNewDotpageRouteImport.update({
  id: '/spaces/new',
  path: '/spaces/new',
  getParentRoute: () => authDotlayoutRoute,
} as any)
const spacesImportDotpageRoute = spacesImportDotpageRouteImport.update({
  id: '/spaces/import',
  path: '/spaces/import',
  getParentRoute: () => authDotlayoutRoute,
} as any)
const usersIndexPageRoute = usersIndexPageRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => authDotlayoutRoute,
} as any)
const spacesIndexPageRoute = spacesIndexPageRouteImport.update({
  id: '/spaces/',
  path: '/spaces/',
  getParentRoute: () => authDotlayoutRoute,
} as any)
const spacesSlugTemplatesPageRoute = spacesSlugTemplatesPageRouteImport.update({
  id: '/spaces/$slug/templates',
  path: '/spaces/$slug/templates',
  getParentRoute: () => authDotlayoutRoute,
} as any)
const spacesSlugSettingsPageRoute = spacesSlugSettingsPageRouteImport.update({
  id: '/spaces/$slug/settings',
  path: '/spaces/$slug/settings',
  getParentRoute: () => authDotlayoutRoute,
} as any)
const spacesSlugMembersDotpageRoute =
  spacesSlugMembersDotpageRouteImport.update({
    id: '/spaces/$slug/members',
    path: '/spaces/$slug/members',
    getParentRoute: () => authDotlayoutRoute,
  } as any)
const spacesSlugExportDotpageRoute = spacesSlugExportDotpageRouteImport.update({
  id: '/spaces/$slug/export',
  path: '/spaces/$slug/export',
  getParentRoute: () => authDotlayoutRoute,
} as any)
const spacesSlugFiltersNewDotpageRoute =
  spacesSlugFiltersNewDotpageRouteImport.update({
    id: '/spaces/$slug/filters/new',
    path: '/spaces/$slug/filters/new',
    getParentRoute: () => authDotlayoutRoute,
  } as any)
const spacesSlugFieldsNewDotpageRoute =
  spacesSlugFieldsNewDotpageRouteImport.update({
    id: '/spaces/$slug/fields/new',
    path: '/spaces/$slug/fields/new',
    getParentRoute: () => authDotlayoutRoute,
  } as any)
const spacesSlugFiltersIndexPageRoute =
  spacesSlugFiltersIndexPageRouteImport.update({
    id: '/spaces/$slug/filters/',
    path: '/spaces/$slug/filters/',
    getParentRoute: () => authDotlayoutRoute,
  } as any)
const spacesSlugFieldsIndexPageRoute =
  spacesSlugFieldsIndexPageRouteImport.update({
    id: '/spaces/$slug/fields/',
    path: '/spaces/$slug/fields/',
    getParentRoute: () => authDotlayoutRoute,
  } as any)
const spacesSlugFiltersFilterNameEditDotpageRoute =
  spacesSlugFiltersFilterNameEditDotpageRouteImport.update({
    id: '/spaces/$slug/filters/$filterName/edit',
    path: '/spaces/$slug/filters/$filterName/edit',
    getParentRoute: () => authDotlayoutRoute,
  } as any)
const spacesSlugFieldsFieldNameEditDotpageRoute =
  spacesSlugFieldsFieldNameEditDotpageRouteImport.update({
    id: '/spaces/$slug/fields/$fieldName/edit',
    path: '/spaces/$slug/fields/$fieldName/edit',
    getParentRoute: () => authDotlayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof loginDotpageRoute
  '/': typeof indexDotpageRoute
  '/pending-attachments': typeof pendingAttachmentsPageRoute
  '/spaces': typeof spacesIndexPageRoute
  '/users': typeof usersIndexPageRoute
  '/spaces/import': typeof spacesImportDotpageRoute
  '/spaces/new': typeof spacesNewDotpageRoute
  '/telegram/mirrors': typeof telegramMirrorsPageRoute
  '/telegram/tasks': typeof telegramTasksPageRoute
  '/users/new': typeof usersNewDotpageRoute
  '/spaces/$slug/export': typeof spacesSlugExportDotpageRoute
  '/spaces/$slug/members': typeof spacesSlugMembersDotpageRoute
  '/spaces/$slug/settings': typeof spacesSlugSettingsPageRoute
  '/spaces/$slug/templates': typeof spacesSlugTemplatesPageRoute
  '/spaces/$slug/fields': typeof spacesSlugFieldsIndexPageRoute
  '/spaces/$slug/filters': typeof spacesSlugFiltersIndexPageRoute
  '/spaces/$slug/fields/new': typeof spacesSlugFieldsNewDotpageRoute
  '/spaces/$slug/filters/new': typeof spacesSlugFiltersNewDotpageRoute
  '/spaces/$slug/fields/$fieldName/edit': typeof spacesSlugFieldsFieldNameEditDotpageRoute
  '/spaces/$slug/filters/$filterName/edit': typeof spacesSlugFiltersFilterNameEditDotpageRoute
}
export interface FileRoutesByTo {
  '/login': typeof loginDotpageRoute
  '/': typeof indexDotpageRoute
  '/pending-attachments': typeof pendingAttachmentsPageRoute
  '/spaces': typeof spacesIndexPageRoute
  '/users': typeof usersIndexPageRoute
  '/spaces/import': typeof spacesImportDotpageRoute
  '/spaces/new': typeof spacesNewDotpageRoute
  '/telegram/mirrors': typeof telegramMirrorsPageRoute
  '/telegram/tasks': typeof telegramTasksPageRoute
  '/users/new': typeof usersNewDotpageRoute
  '/spaces/$slug/export': typeof spacesSlugExportDotpageRoute
  '/spaces/$slug/members': typeof spacesSlugMembersDotpageRoute
  '/spaces/$slug/settings': typeof spacesSlugSettingsPageRoute
  '/spaces/$slug/templates': typeof spacesSlugTemplatesPageRoute
  '/spaces/$slug/fields': typeof spacesSlugFieldsIndexPageRoute
  '/spaces/$slug/filters': typeof spacesSlugFiltersIndexPageRoute
  '/spaces/$slug/fields/new': typeof spacesSlugFieldsNewDotpageRoute
  '/spaces/$slug/filters/new': typeof spacesSlugFiltersNewDotpageRoute
  '/spaces/$slug/fields/$fieldName/edit': typeof spacesSlugFieldsFieldNameEditDotpageRoute
  '/spaces/$slug/filters/$filterName/edit': typeof spacesSlugFiltersFilterNameEditDotpageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth.layout': typeof authDotlayoutRouteWithChildren
  '/login': typeof loginDotpageRoute
  '/_auth.layout/': typeof indexDotpageRoute
  '/_auth.layout/pending-attachments': typeof pendingAttachmentsPageRoute
  '/_auth.layout/spaces/': typeof spacesIndexPageRoute
  '/_auth.layout/users/': typeof usersIndexPageRoute
  '/_auth.layout/spaces/import': typeof spacesImportDotpageRoute
  '/_auth.layout/spaces/new': typeof spacesNewDotpageRoute
  '/_auth.layout/telegram/mirrors': typeof telegramMirrorsPageRoute
  '/_auth.layout/telegram/tasks': typeof telegramTasksPageRoute
  '/_auth.layout/users/new': typeof usersNewDotpageRoute
  '/_auth.layout/spaces/$slug/export': typeof spacesSlugExportDotpageRoute
  '/_auth.layout/spaces/$slug/members': typeof spacesSlugMembersDotpageRoute
  '/_auth.layout/spaces/$slug/settings': typeof spacesSlugSettingsPageRoute
  '/_auth.layout/spaces/$slug/templates': typeof spacesSlugTemplatesPageRoute
  '/_auth.layout/spaces/$slug/fields/': typeof spacesSlugFieldsIndexPageRoute
  '/_auth.layout/spaces/$slug/filters/': typeof spacesSlugFiltersIndexPageRoute
  '/_auth.layout/spaces/$slug/fields/new': typeof spacesSlugFieldsNewDotpageRoute
  '/_auth.layout/spaces/$slug/filters/new': typeof spacesSlugFiltersNewDotpageRoute
  '/_auth.layout/spaces/$slug/fields/$fieldName/edit': typeof spacesSlugFieldsFieldNameEditDotpageRoute
  '/_auth.layout/spaces/$slug/filters/$filterName/edit': typeof spacesSlugFiltersFilterNameEditDotpageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/'
    | '/pending-attachments'
    | '/spaces'
    | '/users'
    | '/spaces/import'
    | '/spaces/new'
    | '/telegram/mirrors'
    | '/telegram/tasks'
    | '/users/new'
    | '/spaces/$slug/export'
    | '/spaces/$slug/members'
    | '/spaces/$slug/settings'
    | '/spaces/$slug/templates'
    | '/spaces/$slug/fields'
    | '/spaces/$slug/filters'
    | '/spaces/$slug/fields/new'
    | '/spaces/$slug/filters/new'
    | '/spaces/$slug/fields/$fieldName/edit'
    | '/spaces/$slug/filters/$filterName/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/pending-attachments'
    | '/spaces'
    | '/users'
    | '/spaces/import'
    | '/spaces/new'
    | '/telegram/mirrors'
    | '/telegram/tasks'
    | '/users/new'
    | '/spaces/$slug/export'
    | '/spaces/$slug/members'
    | '/spaces/$slug/settings'
    | '/spaces/$slug/templates'
    | '/spaces/$slug/fields'
    | '/spaces/$slug/filters'
    | '/spaces/$slug/fields/new'
    | '/spaces/$slug/filters/new'
    | '/spaces/$slug/fields/$fieldName/edit'
    | '/spaces/$slug/filters/$filterName/edit'
  id:
    | '__root__'
    | '/_auth.layout'
    | '/login'
    | '/_auth.layout/'
    | '/_auth.layout/pending-attachments'
    | '/_auth.layout/spaces/'
    | '/_auth.layout/users/'
    | '/_auth.layout/spaces/import'
    | '/_auth.layout/spaces/new'
    | '/_auth.layout/telegram/mirrors'
    | '/_auth.layout/telegram/tasks'
    | '/_auth.layout/users/new'
    | '/_auth.layout/spaces/$slug/export'
    | '/_auth.layout/spaces/$slug/members'
    | '/_auth.layout/spaces/$slug/settings'
    | '/_auth.layout/spaces/$slug/templates'
    | '/_auth.layout/spaces/$slug/fields/'
    | '/_auth.layout/spaces/$slug/filters/'
    | '/_auth.layout/spaces/$slug/fields/new'
    | '/_auth.layout/spaces/$slug/filters/new'
    | '/_auth.layout/spaces/$slug/fields/$fieldName/edit'
    | '/_auth.layout/spaces/$slug/filters/$filterName/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authDotlayoutRoute: typeof authDotlayoutRouteWithChildren
  loginDotpageRoute: typeof loginDotpageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof loginDotpageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth.layout': {
      id: '/_auth.layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authDotlayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth.layout/pending-attachments': {
      id: '/_auth.layout/pending-attachments'
      path: '/pending-attachments'
      fullPath: '/pending-attachments'
      preLoaderRoute: typeof pendingAttachmentsPageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth.layout/': {
      id: '/_auth.layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexDotpageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth.layout/users/new': {
      id: '/_auth.layout/users/new'
      path: '/users/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof usersNewDotpageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth.layout/telegram/tasks': {
      id: '/_auth.layout/telegram/tasks'
      path: '/telegram/tasks'
      fullPath: '/telegram/tasks'
      preLoaderRoute: typeof telegramTasksPageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth.layout/telegram/mirrors': {
      id: '/_auth.layout/telegram/mirrors'
      path: '/telegram/mirrors'
      fullPath: '/telegram/mirrors'
      preLoaderRoute: typeof telegramMirrorsPageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth.layout/spaces/new': {
      id: '/_auth.layout/spaces/new'
      path: '/spaces/new'
      fullPath: '/spaces/new'
      preLoaderRoute: typeof spacesNewDotpageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth.layout/spaces/import': {
      id: '/_auth.layout/spaces/import'
      path: '/spaces/import'
      fullPath: '/spaces/import'
      preLoaderRoute: typeof spacesImportDotpageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth.layout/users/': {
      id: '/_auth.layout/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof usersIndexPageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth.layout/spaces/': {
      id: '/_auth.layout/spaces/'
      path: '/spaces'
      fullPath: '/spaces'
      preLoaderRoute: typeof spacesIndexPageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth.layout/spaces/$slug/templates': {
      id: '/_auth.layout/spaces/$slug/templates'
      path: '/spaces/$slug/templates'
      fullPath: '/spaces/$slug/templates'
      preLoaderRoute: typeof spacesSlugTemplatesPageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth.layout/spaces/$slug/settings': {
      id: '/_auth.layout/spaces/$slug/settings'
      path: '/spaces/$slug/settings'
      fullPath: '/spaces/$slug/settings'
      preLoaderRoute: typeof spacesSlugSettingsPageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth.layout/spaces/$slug/members': {
      id: '/_auth.layout/spaces/$slug/members'
      path: '/spaces/$slug/members'
      fullPath: '/spaces/$slug/members'
      preLoaderRoute: typeof spacesSlugMembersDotpageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth.layout/spaces/$slug/export': {
      id: '/_auth.layout/spaces/$slug/export'
      path: '/spaces/$slug/export'
      fullPath: '/spaces/$slug/export'
      preLoaderRoute: typeof spacesSlugExportDotpageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth.layout/spaces/$slug/filters/new': {
      id: '/_auth.layout/spaces/$slug/filters/new'
      path: '/spaces/$slug/filters/new'
      fullPath: '/spaces/$slug/filters/new'
      preLoaderRoute: typeof spacesSlugFiltersNewDotpageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth.layout/spaces/$slug/fields/new': {
      id: '/_auth.layout/spaces/$slug/fields/new'
      path: '/spaces/$slug/fields/new'
      fullPath: '/spaces/$slug/fields/new'
      preLoaderRoute: typeof spacesSlugFieldsNewDotpageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth.layout/spaces/$slug/filters/': {
      id: '/_auth.layout/spaces/$slug/filters/'
      path: '/spaces/$slug/filters'
      fullPath: '/spaces/$slug/filters'
      preLoaderRoute: typeof spacesSlugFiltersIndexPageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth.layout/spaces/$slug/fields/': {
      id: '/_auth.layout/spaces/$slug/fields/'
      path: '/spaces/$slug/fields'
      fullPath: '/spaces/$slug/fields'
      preLoaderRoute: typeof spacesSlugFieldsIndexPageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth.layout/spaces/$slug/filters/$filterName/edit': {
      id: '/_auth.layout/spaces/$slug/filters/$filterName/edit'
      path: '/spaces/$slug/filters/$filterName/edit'
      fullPath: '/spaces/$slug/filters/$filterName/edit'
      preLoaderRoute: typeof spacesSlugFiltersFilterNameEditDotpageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth.layout/spaces/$slug/fields/$fieldName/edit': {
      id: '/_auth.layout/spaces/$slug/fields/$fieldName/edit'
      path: '/spaces/$slug/fields/$fieldName/edit'
      fullPath: '/spaces/$slug/fields/$fieldName/edit'
      preLoaderRoute: typeof spacesSlugFieldsFieldNameEditDotpageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
  }
}

interface authDotlayoutRouteChildren {
  indexDotpageRoute: typeof indexDotpageRoute
  pendingAttachmentsPageRoute: typeof pendingAttachmentsPageRoute
  spacesIndexPageRoute: typeof spacesIndexPageRoute
  usersIndexPageRoute: typeof usersIndexPageRoute
  spacesImportDotpageRoute: typeof spacesImportDotpageRoute
  spacesNewDotpageRoute: typeof spacesNewDotpageRoute
  telegramMirrorsPageRoute: typeof telegramMirrorsPageRoute
  telegramTasksPageRoute: typeof telegramTasksPageRoute
  usersNewDotpageRoute: typeof usersNewDotpageRoute
  spacesSlugExportDotpageRoute: typeof spacesSlugExportDotpageRoute
  spacesSlugMembersDotpageRoute: typeof spacesSlugMembersDotpageRoute
  spacesSlugSettingsPageRoute: typeof spacesSlugSettingsPageRoute
  spacesSlugTemplatesPageRoute: typeof spacesSlugTemplatesPageRoute
  spacesSlugFieldsIndexPageRoute: typeof spacesSlugFieldsIndexPageRoute
  spacesSlugFiltersIndexPageRoute: typeof spacesSlugFiltersIndexPageRoute
  spacesSlugFieldsNewDotpageRoute: typeof spacesSlugFieldsNewDotpageRoute
  spacesSlugFiltersNewDotpageRoute: typeof spacesSlugFiltersNewDotpageRoute
  spacesSlugFieldsFieldNameEditDotpageRoute: typeof spacesSlugFieldsFieldNameEditDotpageRoute
  spacesSlugFiltersFilterNameEditDotpageRoute: typeof spacesSlugFiltersFilterNameEditDotpageRoute
}

const authDotlayoutRouteChildren: authDotlayoutRouteChildren = {
  indexDotpageRoute: indexDotpageRoute,
  pendingAttachmentsPageRoute: pendingAttachmentsPageRoute,
  spacesIndexPageRoute: spacesIndexPageRoute,
  usersIndexPageRoute: usersIndexPageRoute,
  spacesImportDotpageRoute: spacesImportDotpageRoute,
  spacesNewDotpageRoute: spacesNewDotpageRoute,
  telegramMirrorsPageRoute: telegramMirrorsPageRoute,
  telegramTasksPageRoute: telegramTasksPageRoute,
  usersNewDotpageRoute: usersNewDotpageRoute,
  spacesSlugExportDotpageRoute: spacesSlugExportDotpageRoute,
  spacesSlugMembersDotpageRoute: spacesSlugMembersDotpageRoute,
  spacesSlugSettingsPageRoute: spacesSlugSettingsPageRoute,
  spacesSlugTemplatesPageRoute: spacesSlugTemplatesPageRoute,
  spacesSlugFieldsIndexPageRoute: spacesSlugFieldsIndexPageRoute,
  spacesSlugFiltersIndexPageRoute: spacesSlugFiltersIndexPageRoute,
  spacesSlugFieldsNewDotpageRoute: spacesSlugFieldsNewDotpageRoute,
  spacesSlugFiltersNewDotpageRoute: spacesSlugFiltersNewDotpageRoute,
  spacesSlugFieldsFieldNameEditDotpageRoute:
    spacesSlugFieldsFieldNameEditDotpageRoute,
  spacesSlugFiltersFilterNameEditDotpageRoute:
    spacesSlugFiltersFilterNameEditDotpageRoute,
}

const authDotlayoutRouteWithChildren = authDotlayoutRoute._addFileChildren(
  authDotlayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authDotlayoutRoute: authDotlayoutRouteWithChildren,
  loginDotpageRoute: loginDotpageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
