/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
  "/api/v1/auth/login": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Authenticate user
     * @description Authenticate with username and password to receive an authentication token.
     */
    post: operations["login"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/auth/logout": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * End session
     * @description Invalidate the current authentication session.
     */
    post: operations["logout"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/spaces/{space_slug}/notes/{note_number}/comments": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List note comments
     * @description Get paginated comments for a note. Only space members can view comments.
     */
    get: operations["listComments"]
    put?: never
    /**
     * Create new comment
     * @description Create a new comment on a note. Only space members can comment.
     */
    post: operations["createComment"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/spaces/{space_slug}/notes/{note_number}/comments/{number}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get comment by number
     * @description Get a specific comment by its number. Only space members can view comments.
     */
    get: operations["getComment"]
    put?: never
    post?: never
    /**
     * Delete comment
     * @description Delete a comment. Only the comment author can delete. Replies are orphaned.
     */
    delete: operations["deleteComment"]
    options?: never
    head?: never
    /**
     * Update comment
     * @description Update comment content. Only the comment author can update.
     */
    patch: operations["updateComment"]
    trace?: never
  }
  "/api/v1/spaces/{space_slug}/fields": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Add field to space
     * @description Add a new field definition to an existing space. Only accessible by admin users.
     */
    post: operations["addFieldToSpace"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/spaces/{space_slug}/fields/{field_name}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Remove field from space
     * @description Remove a field definition from a space. Only accessible by admin users.
     */
    delete: operations["removeFieldFromSpace"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/spaces/{space_slug}/notes": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List space notes
     * @description Get paginated notes in a space. Only space members can view notes.
     */
    get: operations["listNotes"]
    put?: never
    /**
     * Create new note
     * @description Create a new note in a space with the provided field values. Only space members can create notes.
     */
    post: operations["createNote"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/spaces/{space_slug}/notes/{number}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get note by number
     * @description Get a specific note by its number within a space. Only space members can view notes.
     */
    get: operations["getNote"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * Update note fields
     * @description Partially update note fields. Only provided fields will be updated. Members only.
     */
    patch: operations["updateNote"]
    trace?: never
  }
  "/api/v1/profile": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get current user profile
     * @description Get the profile of the currently authenticated user
     */
    get: operations["getCurrentUserProfile"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/profile/change-password": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Change password
     * @description Change the password for the currently authenticated user
     */
    post: operations["changePassword"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/spaces": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List spaces
     * @description Get all spaces. Admin sees all spaces, regular users see only spaces where they are members.
     */
    get: operations["listSpaces"]
    put?: never
    /**
     * Create new space
     * @description Create a new space. Only accessible by admin users.
     */
    post: operations["createSpace"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/spaces/{slug}/title": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * Update space title
     * @description Update space title. Only accessible by admin users.
     */
    patch: operations["updateSpaceTitle"]
    trace?: never
  }
  "/api/v1/spaces/{slug}/description": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * Update space description
     * @description Update space description. Only accessible by admin users.
     */
    patch: operations["updateSpaceDescription"]
    trace?: never
  }
  "/api/v1/spaces/{slug}/members": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * Update space members
     * @description Update space members list. Only accessible by admin users.
     */
    patch: operations["updateSpaceMembers"]
    trace?: never
  }
  "/api/v1/spaces/{slug}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete space
     * @description Delete a space. Only accessible by admin users.
     */
    delete: operations["deleteSpace"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/users": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List all users
     * @description Get all users in the system
     */
    get: operations["listUsers"]
    put?: never
    /**
     * Create new user
     * @description Create a new user account. Only accessible by admin users.
     */
    post: operations["createUser"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/users/{username}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete user
     * @description Delete a user account. Only accessible by admin users.
     */
    delete: operations["deleteUser"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/health": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health Check */
    get: operations["health_check_health_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export type components = {
  schemas: {
    /**
     * ChangePasswordRequest
     * @description Password change request.
     */
    ChangePasswordRequest: {
      /**
       * Old Password
       * @description Current password
       */
      old_password: string
      /**
       * New Password
       * @description New password
       */
      new_password: string
    }
    /**
     * Comment
     * @description Comment on a note with optional threading support.
     */
    Comment: {
      /** Space Slug */
      space_slug: string
      /** Note Number */
      note_number: number
      /** Number */
      number: number
      /** Author */
      author: string
      /** Content */
      content: string
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Edited At */
      edited_at: string | null
      /** Parent Number */
      parent_number: number | null
    }
    /**
     * CreateCommentRequest
     * @description Request to create a new comment.
     */
    CreateCommentRequest: {
      /**
       * Content
       * @description Comment content
       */
      content: string
      /**
       * Parent Number
       * @description Parent comment number for threading
       */
      parent_number?: number | null
    }
    /**
     * CreateNoteRequest
     * @description Request to create a new note.
     */
    CreateNoteRequest: {
      /**
       * Raw Fields
       * @description Field values as raw strings (will be parsed according to field types)
       */
      raw_fields: {
        [key: string]: string
      }
    }
    /**
     * CreateSpaceRequest
     * @description Space creation request.
     */
    CreateSpaceRequest: {
      /**
       * Slug
       * @description URL-friendly unique identifier for the space
       */
      slug: string
      /**
       * Title
       * @description Space title
       */
      title: string
      /**
       * Description
       * @description Space description
       * @default
       */
      description: string
      /**
       * Members
       * @description List of member usernames
       */
      members?: string[]
    }
    /**
     * CreateUserRequest
     * @description User creation request.
     */
    CreateUserRequest: {
      /**
       * Username
       * @description Username for the new user
       */
      username: string
      /**
       * Password
       * @description Password for the new user
       */
      password: string
    }
    /**
     * ErrorResponse
     * @description Standard error response format.
     * @example {
     *       "message": "Invalid credentials",
     *       "type": "authentication_error"
     *     }
     * @example {
     *       "message": "Space not found",
     *       "type": "not_found"
     *     }
     * @example {
     *       "message": "Access denied",
     *       "type": "access_denied"
     *     }
     */
    ErrorResponse: {
      /**
       * Message
       * @description Human-readable error message
       */
      message: string
      /**
       * Type
       * @description Machine-readable error type
       */
      type: string
    }
    /**
     * FieldOption
     * @description Configuration options for field types.
     * @enum {string}
     */
    FieldOption: "values" | "min" | "max" | "value_maps" | "max_width"
    /**
     * FieldType
     * @description Available field types for space schemas.
     * @enum {string}
     */
    FieldType: "string" | "markdown" | "boolean" | "select" | "tags" | "user" | "datetime" | "int" | "float" | "image"
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][]
    }
    /**
     * LoginRequest
     * @description Authentication request.
     */
    LoginRequest: {
      /**
       * Username
       * @description Username for authentication
       */
      username: string
      /**
       * Password
       * @description Password for authentication
       */
      password: string
    }
    /**
     * LoginResponse
     * @description Authentication response.
     */
    LoginResponse: {
      /**
       * Token
       * @description Authentication token for subsequent requests
       */
      token: string
    }
    /**
     * Note
     * @description Note with custom fields stored in a space.
     */
    Note: {
      /** Space Slug */
      space_slug: string
      /** Number */
      number: number
      /** Author */
      author: string
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Edited At */
      edited_at: string | null
      /** Fields */
      fields: {
        [key: string]: string | boolean | string[] | number | null
      }
    }
    /** PaginationResult[Comment] */
    PaginationResult_Comment_: {
      /**
       * Items
       * @description List of items in current page
       */
      items: components["schemas"]["Comment"][]
      /**
       * Total
       * @description Total number of items across all pages
       */
      total: number
      /**
       * Limit
       * @description Maximum items per page
       */
      limit: number
      /**
       * Offset
       * @description Number of items skipped
       */
      offset: number
    }
    /** PaginationResult[Note] */
    PaginationResult_Note_: {
      /**
       * Items
       * @description List of items in current page
       */
      items: components["schemas"]["Note"][]
      /**
       * Total
       * @description Total number of items across all pages
       */
      total: number
      /**
       * Limit
       * @description Maximum items per page
       */
      limit: number
      /**
       * Offset
       * @description Number of items skipped
       */
      offset: number
    }
    /**
     * Space
     * @description Space entity.
     */
    Space: {
      /**
       * Slug
       * @description URL-friendly unique identifier for the space (lowercase, hyphens, alphanumeric)
       */
      slug: string
      /**
       * Title
       * @description Space title
       */
      title: string
      /**
       * Description
       * @description Space description
       * @default
       */
      description: string
      /**
       * Members
       * @description List of member usernames who have access to this space
       */
      members: string[]
      /**
       * Fields
       * @description Field definitions for notes in this space
       */
      fields: components["schemas"]["SpaceField"][]
      /**
       * Created At
       * Format: date-time
       * @description Timestamp when the space was created
       */
      created_at: string
    }
    /**
     * SpaceField
     * @description Field definition in a space schema.
     */
    SpaceField: {
      /**
       * Name
       * @description Field identifier (must be unique within space)
       */
      name: string
      /** @description Field data type */
      type: components["schemas"]["FieldType"]
      /**
       * Required
       * @description Whether this field is required
       * @default false
       */
      required: boolean
      /**
       * Options
       * @description Field type-specific options (e.g., 'values' for select, 'min'/'max' for numeric types, 'value_maps' for select metadata, 'max_width' for image)
       */
      options?: {
        [key: string]:
          | string[]
          | number
          | {
              [key: string]: {
                [key: string]: string
              }
            }
      }
      /**
       * Default
       * @description Default value for this field
       */
      default?: string | boolean | string[] | number | null
    }
    /**
     * UpdateCommentRequest
     * @description Request to update comment content.
     */
    UpdateCommentRequest: {
      /**
       * Content
       * @description Updated comment content
       */
      content: string
    }
    /**
     * UpdateDescriptionRequest
     * @description Space description update request.
     */
    UpdateDescriptionRequest: {
      /**
       * Description
       * @description New space description
       */
      description: string
    }
    /**
     * UpdateMembersRequest
     * @description Space members update request.
     */
    UpdateMembersRequest: {
      /**
       * Members
       * @description New list of member usernames
       */
      members: string[]
    }
    /**
     * UpdateNoteRequest
     * @description Request to update note fields (partial update).
     */
    UpdateNoteRequest: {
      /**
       * Raw Fields
       * @description Field values to update as raw strings. Only provided fields will be updated.
       */
      raw_fields: {
        [key: string]: string
      }
    }
    /**
     * UpdateTitleRequest
     * @description Space title update request.
     */
    UpdateTitleRequest: {
      /**
       * Title
       * @description New space title
       */
      title: string
    }
    /**
     * UserView
     * @description User account information (API representation).
     */
    UserView: {
      /**
       * Username
       * @description Username
       */
      username: string
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"]
      }
    }
    responses: {
      /** @description Successfully authenticated */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["LoginResponse"]
        }
      }
      /** @description Invalid credentials */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  logout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successfully logged out */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
    }
  }
  listComments: {
    parameters: {
      query?: {
        /** @description Maximum items to return */
        limit?: number
        /** @description Number of items to skip */
        offset?: number
      }
      header?: never
      path: {
        space_slug: string
        note_number: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Paginated list of comments */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PaginationResult_Comment_"]
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Not a member of this space */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Space or note not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  createComment: {
    parameters: {
      query?: never
      header?: never
      path: {
        space_slug: string
        note_number: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateCommentRequest"]
      }
    }
    responses: {
      /** @description Comment created successfully */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Comment"]
        }
      }
      /** @description Invalid parent comment */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Not a member of this space */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Space or note not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  getComment: {
    parameters: {
      query?: never
      header?: never
      path: {
        space_slug: string
        note_number: number
        number: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Comment details */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Comment"]
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Not a member of this space */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Space, note, or comment not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  deleteComment: {
    parameters: {
      query?: never
      header?: never
      path: {
        space_slug: string
        note_number: number
        number: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Comment deleted successfully */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Not the comment author */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Space, note, or comment not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  updateComment: {
    parameters: {
      query?: never
      header?: never
      path: {
        space_slug: string
        note_number: number
        number: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateCommentRequest"]
      }
    }
    responses: {
      /** @description Comment updated successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Comment"]
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Not the comment author */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Space, note, or comment not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  addFieldToSpace: {
    parameters: {
      query?: never
      header?: never
      path: {
        space_slug: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["SpaceField"]
      }
    }
    responses: {
      /** @description Field added successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Space"]
        }
      }
      /** @description Invalid field data or field name already exists */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Admin privileges required */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Space not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  removeFieldFromSpace: {
    parameters: {
      query?: never
      header?: never
      path: {
        space_slug: string
        field_name: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Field removed successfully */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Admin privileges required */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Space or field not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  listNotes: {
    parameters: {
      query?: {
        /** @description Maximum items to return */
        limit?: number
        /** @description Number of items to skip */
        offset?: number
      }
      header?: never
      path: {
        space_slug: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Paginated list of notes */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PaginationResult_Note_"]
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Not a member of this space */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Space not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  createNote: {
    parameters: {
      query?: never
      header?: never
      path: {
        space_slug: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateNoteRequest"]
      }
    }
    responses: {
      /** @description Note created successfully */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Note"]
        }
      }
      /** @description Invalid field data or validation failed */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Not a member of this space */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Space not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  getNote: {
    parameters: {
      query?: never
      header?: never
      path: {
        space_slug: string
        number: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Note details */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Note"]
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Not a member of this space */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Space or note not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  updateNote: {
    parameters: {
      query?: never
      header?: never
      path: {
        space_slug: string
        number: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateNoteRequest"]
      }
    }
    responses: {
      /** @description Note updated successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Note"]
        }
      }
      /** @description Invalid field data or validation failed */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Not a member of this space */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Space or note not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  getCurrentUserProfile: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Current user profile */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["UserView"]
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
    }
  }
  changePassword: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangePasswordRequest"]
      }
    }
    responses: {
      /** @description Password changed successfully */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Invalid request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Not authenticated or invalid current password */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  listSpaces: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of spaces */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Space"][]
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
    }
  }
  createSpace: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateSpaceRequest"]
      }
    }
    responses: {
      /** @description Space created successfully */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Space"]
        }
      }
      /** @description Invalid request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Admin privileges required */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  updateSpaceTitle: {
    parameters: {
      query?: never
      header?: never
      path: {
        slug: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateTitleRequest"]
      }
    }
    responses: {
      /** @description Space title updated successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Space"]
        }
      }
      /** @description Invalid request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Admin privileges required */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Space not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  updateSpaceDescription: {
    parameters: {
      query?: never
      header?: never
      path: {
        slug: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateDescriptionRequest"]
      }
    }
    responses: {
      /** @description Space description updated successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Space"]
        }
      }
      /** @description Invalid request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Admin privileges required */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Space not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  updateSpaceMembers: {
    parameters: {
      query?: never
      header?: never
      path: {
        slug: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateMembersRequest"]
      }
    }
    responses: {
      /** @description Space members updated successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Space"]
        }
      }
      /** @description Invalid request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Admin privileges required */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Space not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  deleteSpace: {
    parameters: {
      query?: never
      header?: never
      path: {
        slug: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Space deleted successfully */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Admin privileges required */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Space not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  listUsers: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of all users */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["UserView"][]
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
    }
  }
  createUser: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUserRequest"]
      }
    }
    responses: {
      /** @description User created successfully */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["UserView"]
        }
      }
      /** @description Invalid request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Admin privileges required */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  deleteUser: {
    parameters: {
      query?: never
      header?: never
      path: {
        username: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description User deleted successfully */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Cannot delete user (self-deletion) */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Admin privileges required */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  health_check_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
    }
  }
}
