/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthSSlugIndexRouteImport } from './routes/_auth/s/$slug/index'
import { Route as AuthSSlugNewRouteImport } from './routes/_auth/s/$slug/new'
import { Route as AuthSSlugNoteNumberRouteRouteImport } from './routes/_auth/s/$slug/$noteNumber/route'
import { Route as AuthSSlugAttachmentsIndexRouteImport } from './routes/_auth/s/$slug/attachments/index'
import { Route as AuthSSlugAttachmentsNewRouteImport } from './routes/_auth/s/$slug/attachments/new'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSSlugIndexRoute = AuthSSlugIndexRouteImport.update({
  id: '/s/$slug/',
  path: '/s/$slug/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSSlugNewRoute = AuthSSlugNewRouteImport.update({
  id: '/s/$slug/new',
  path: '/s/$slug/new',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSSlugNoteNumberRouteRoute =
  AuthSSlugNoteNumberRouteRouteImport.update({
    id: '/s/$slug/$noteNumber',
    path: '/s/$slug/$noteNumber',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthSSlugAttachmentsIndexRoute =
  AuthSSlugAttachmentsIndexRouteImport.update({
    id: '/s/$slug/attachments/',
    path: '/s/$slug/attachments/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthSSlugAttachmentsNewRoute = AuthSSlugAttachmentsNewRouteImport.update({
  id: '/s/$slug/attachments/new',
  path: '/s/$slug/attachments/new',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/': typeof AuthIndexRoute
  '/s/$slug/$noteNumber': typeof AuthSSlugNoteNumberRouteRoute
  '/s/$slug/new': typeof AuthSSlugNewRoute
  '/s/$slug': typeof AuthSSlugIndexRoute
  '/s/$slug/attachments/new': typeof AuthSSlugAttachmentsNewRoute
  '/s/$slug/attachments': typeof AuthSSlugAttachmentsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthIndexRoute
  '/s/$slug/$noteNumber': typeof AuthSSlugNoteNumberRouteRoute
  '/s/$slug/new': typeof AuthSSlugNewRoute
  '/s/$slug': typeof AuthSSlugIndexRoute
  '/s/$slug/attachments/new': typeof AuthSSlugAttachmentsNewRoute
  '/s/$slug/attachments': typeof AuthSSlugAttachmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/s/$slug/$noteNumber': typeof AuthSSlugNoteNumberRouteRoute
  '/_auth/s/$slug/new': typeof AuthSSlugNewRoute
  '/_auth/s/$slug/': typeof AuthSSlugIndexRoute
  '/_auth/s/$slug/attachments/new': typeof AuthSSlugAttachmentsNewRoute
  '/_auth/s/$slug/attachments/': typeof AuthSSlugAttachmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/'
    | '/s/$slug/$noteNumber'
    | '/s/$slug/new'
    | '/s/$slug'
    | '/s/$slug/attachments/new'
    | '/s/$slug/attachments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/s/$slug/$noteNumber'
    | '/s/$slug/new'
    | '/s/$slug'
    | '/s/$slug/attachments/new'
    | '/s/$slug/attachments'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/'
    | '/_auth/s/$slug/$noteNumber'
    | '/_auth/s/$slug/new'
    | '/_auth/s/$slug/'
    | '/_auth/s/$slug/attachments/new'
    | '/_auth/s/$slug/attachments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/s/$slug/': {
      id: '/_auth/s/$slug/'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof AuthSSlugIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/s/$slug/new': {
      id: '/_auth/s/$slug/new'
      path: '/s/$slug/new'
      fullPath: '/s/$slug/new'
      preLoaderRoute: typeof AuthSSlugNewRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/s/$slug/$noteNumber': {
      id: '/_auth/s/$slug/$noteNumber'
      path: '/s/$slug/$noteNumber'
      fullPath: '/s/$slug/$noteNumber'
      preLoaderRoute: typeof AuthSSlugNoteNumberRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/s/$slug/attachments/': {
      id: '/_auth/s/$slug/attachments/'
      path: '/s/$slug/attachments'
      fullPath: '/s/$slug/attachments'
      preLoaderRoute: typeof AuthSSlugAttachmentsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/s/$slug/attachments/new': {
      id: '/_auth/s/$slug/attachments/new'
      path: '/s/$slug/attachments/new'
      fullPath: '/s/$slug/attachments/new'
      preLoaderRoute: typeof AuthSSlugAttachmentsNewRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthSSlugNoteNumberRouteRoute: typeof AuthSSlugNoteNumberRouteRoute
  AuthSSlugNewRoute: typeof AuthSSlugNewRoute
  AuthSSlugIndexRoute: typeof AuthSSlugIndexRoute
  AuthSSlugAttachmentsNewRoute: typeof AuthSSlugAttachmentsNewRoute
  AuthSSlugAttachmentsIndexRoute: typeof AuthSSlugAttachmentsIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthSSlugNoteNumberRouteRoute: AuthSSlugNoteNumberRouteRoute,
  AuthSSlugNewRoute: AuthSSlugNewRoute,
  AuthSSlugIndexRoute: AuthSSlugIndexRoute,
  AuthSSlugAttachmentsNewRoute: AuthSSlugAttachmentsNewRoute,
  AuthSSlugAttachmentsIndexRoute: AuthSSlugAttachmentsIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
