/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/root.layout'
import { Route as loginDotpageRouteImport } from './routes/login.page'
import { Route as authDotlayoutRouteImport } from './routes/auth.layout'
import { Route as indexPageRouteImport } from './routes/index/page'
import { Route as sSlugNewDotpageRouteImport } from './routes/s/_slug_/new.page'
import { Route as sSlugIndexPageRouteImport } from './routes/s/_slug_/index/page'
import { Route as sSlugAttachmentsIndexDotpageRouteImport } from './routes/s/_slug_/attachments/index.page'
import { Route as sSlugAttachmentsNewDotpageRouteImport } from './routes/s/_slug_/attachments/new.page'
import { Route as sSlug_noteNumberEditDotpageRouteImport } from './routes/s/_slug_/_noteNumber_/edit.page'
import { Route as sSlug_noteNumberIndexPageRouteImport } from './routes/s/_slug_/_noteNumber_/index/page'
import { Route as sSlug_noteNumberAttachmentsIndexDotpageRouteImport } from './routes/s/_slug_/_noteNumber_/attachments/index.page'
import { Route as sSlug_noteNumberAttachmentsNewDotpageRouteImport } from './routes/s/_slug_/_noteNumber_/attachments/new.page'

const loginDotpageRoute = loginDotpageRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authDotlayoutRoute = authDotlayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const indexPageRoute = indexPageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authDotlayoutRoute,
} as any)
const sSlugNewDotpageRoute = sSlugNewDotpageRouteImport.update({
  id: '/s/$slug/new',
  path: '/s/$slug/new',
  getParentRoute: () => authDotlayoutRoute,
} as any)
const sSlugIndexPageRoute = sSlugIndexPageRouteImport.update({
  id: '/s/$slug/',
  path: '/s/$slug/',
  getParentRoute: () => authDotlayoutRoute,
} as any)
const sSlugAttachmentsIndexDotpageRoute =
  sSlugAttachmentsIndexDotpageRouteImport.update({
    id: '/s/$slug/attachments/',
    path: '/s/$slug/attachments/',
    getParentRoute: () => authDotlayoutRoute,
  } as any)
const sSlugAttachmentsNewDotpageRoute =
  sSlugAttachmentsNewDotpageRouteImport.update({
    id: '/s/$slug/attachments/new',
    path: '/s/$slug/attachments/new',
    getParentRoute: () => authDotlayoutRoute,
  } as any)
const sSlug_noteNumberEditDotpageRoute =
  sSlug_noteNumberEditDotpageRouteImport.update({
    id: '/s/$slug/$noteNumber/edit',
    path: '/s/$slug/$noteNumber/edit',
    getParentRoute: () => authDotlayoutRoute,
  } as any)
const sSlug_noteNumberIndexPageRoute =
  sSlug_noteNumberIndexPageRouteImport.update({
    id: '/s/$slug/$noteNumber/',
    path: '/s/$slug/$noteNumber/',
    getParentRoute: () => authDotlayoutRoute,
  } as any)
const sSlug_noteNumberAttachmentsIndexDotpageRoute =
  sSlug_noteNumberAttachmentsIndexDotpageRouteImport.update({
    id: '/s/$slug/$noteNumber/attachments/',
    path: '/s/$slug/$noteNumber/attachments/',
    getParentRoute: () => authDotlayoutRoute,
  } as any)
const sSlug_noteNumberAttachmentsNewDotpageRoute =
  sSlug_noteNumberAttachmentsNewDotpageRouteImport.update({
    id: '/s/$slug/$noteNumber/attachments/new',
    path: '/s/$slug/$noteNumber/attachments/new',
    getParentRoute: () => authDotlayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof loginDotpageRoute
  '/': typeof indexPageRoute
  '/s/$slug': typeof sSlugIndexPageRoute
  '/s/$slug/new': typeof sSlugNewDotpageRoute
  '/s/$slug/$noteNumber': typeof sSlug_noteNumberIndexPageRoute
  '/s/$slug/$noteNumber/edit': typeof sSlug_noteNumberEditDotpageRoute
  '/s/$slug/attachments/new': typeof sSlugAttachmentsNewDotpageRoute
  '/s/$slug/attachments': typeof sSlugAttachmentsIndexDotpageRoute
  '/s/$slug/$noteNumber/attachments/new': typeof sSlug_noteNumberAttachmentsNewDotpageRoute
  '/s/$slug/$noteNumber/attachments': typeof sSlug_noteNumberAttachmentsIndexDotpageRoute
}
export interface FileRoutesByTo {
  '/login': typeof loginDotpageRoute
  '/': typeof indexPageRoute
  '/s/$slug': typeof sSlugIndexPageRoute
  '/s/$slug/new': typeof sSlugNewDotpageRoute
  '/s/$slug/$noteNumber': typeof sSlug_noteNumberIndexPageRoute
  '/s/$slug/$noteNumber/edit': typeof sSlug_noteNumberEditDotpageRoute
  '/s/$slug/attachments/new': typeof sSlugAttachmentsNewDotpageRoute
  '/s/$slug/attachments': typeof sSlugAttachmentsIndexDotpageRoute
  '/s/$slug/$noteNumber/attachments/new': typeof sSlug_noteNumberAttachmentsNewDotpageRoute
  '/s/$slug/$noteNumber/attachments': typeof sSlug_noteNumberAttachmentsIndexDotpageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof authDotlayoutRouteWithChildren
  '/login': typeof loginDotpageRoute
  '/_auth/': typeof indexPageRoute
  '/_auth/s/$slug/': typeof sSlugIndexPageRoute
  '/_auth/s/$slug/new': typeof sSlugNewDotpageRoute
  '/_auth/s/$slug/$noteNumber/': typeof sSlug_noteNumberIndexPageRoute
  '/_auth/s/$slug/$noteNumber/edit': typeof sSlug_noteNumberEditDotpageRoute
  '/_auth/s/$slug/attachments/new': typeof sSlugAttachmentsNewDotpageRoute
  '/_auth/s/$slug/attachments/': typeof sSlugAttachmentsIndexDotpageRoute
  '/_auth/s/$slug/$noteNumber/attachments/new': typeof sSlug_noteNumberAttachmentsNewDotpageRoute
  '/_auth/s/$slug/$noteNumber/attachments/': typeof sSlug_noteNumberAttachmentsIndexDotpageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/'
    | '/s/$slug'
    | '/s/$slug/new'
    | '/s/$slug/$noteNumber'
    | '/s/$slug/$noteNumber/edit'
    | '/s/$slug/attachments/new'
    | '/s/$slug/attachments'
    | '/s/$slug/$noteNumber/attachments/new'
    | '/s/$slug/$noteNumber/attachments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/s/$slug'
    | '/s/$slug/new'
    | '/s/$slug/$noteNumber'
    | '/s/$slug/$noteNumber/edit'
    | '/s/$slug/attachments/new'
    | '/s/$slug/attachments'
    | '/s/$slug/$noteNumber/attachments/new'
    | '/s/$slug/$noteNumber/attachments'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/'
    | '/_auth/s/$slug/'
    | '/_auth/s/$slug/new'
    | '/_auth/s/$slug/$noteNumber/'
    | '/_auth/s/$slug/$noteNumber/edit'
    | '/_auth/s/$slug/attachments/new'
    | '/_auth/s/$slug/attachments/'
    | '/_auth/s/$slug/$noteNumber/attachments/new'
    | '/_auth/s/$slug/$noteNumber/attachments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authDotlayoutRoute: typeof authDotlayoutRouteWithChildren
  loginDotpageRoute: typeof loginDotpageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof loginDotpageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authDotlayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexPageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth/s/$slug/new': {
      id: '/_auth/s/$slug/new'
      path: '/s/$slug/new'
      fullPath: '/s/$slug/new'
      preLoaderRoute: typeof sSlugNewDotpageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth/s/$slug/': {
      id: '/_auth/s/$slug/'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof sSlugIndexPageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth/s/$slug/attachments/': {
      id: '/_auth/s/$slug/attachments/'
      path: '/s/$slug/attachments'
      fullPath: '/s/$slug/attachments'
      preLoaderRoute: typeof sSlugAttachmentsIndexDotpageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth/s/$slug/attachments/new': {
      id: '/_auth/s/$slug/attachments/new'
      path: '/s/$slug/attachments/new'
      fullPath: '/s/$slug/attachments/new'
      preLoaderRoute: typeof sSlugAttachmentsNewDotpageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth/s/$slug/$noteNumber/edit': {
      id: '/_auth/s/$slug/$noteNumber/edit'
      path: '/s/$slug/$noteNumber/edit'
      fullPath: '/s/$slug/$noteNumber/edit'
      preLoaderRoute: typeof sSlug_noteNumberEditDotpageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth/s/$slug/$noteNumber/': {
      id: '/_auth/s/$slug/$noteNumber/'
      path: '/s/$slug/$noteNumber'
      fullPath: '/s/$slug/$noteNumber'
      preLoaderRoute: typeof sSlug_noteNumberIndexPageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth/s/$slug/$noteNumber/attachments/': {
      id: '/_auth/s/$slug/$noteNumber/attachments/'
      path: '/s/$slug/$noteNumber/attachments'
      fullPath: '/s/$slug/$noteNumber/attachments'
      preLoaderRoute: typeof sSlug_noteNumberAttachmentsIndexDotpageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth/s/$slug/$noteNumber/attachments/new': {
      id: '/_auth/s/$slug/$noteNumber/attachments/new'
      path: '/s/$slug/$noteNumber/attachments/new'
      fullPath: '/s/$slug/$noteNumber/attachments/new'
      preLoaderRoute: typeof sSlug_noteNumberAttachmentsNewDotpageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
  }
}

interface authDotlayoutRouteChildren {
  indexPageRoute: typeof indexPageRoute
  sSlugIndexPageRoute: typeof sSlugIndexPageRoute
  sSlugNewDotpageRoute: typeof sSlugNewDotpageRoute
  sSlug_noteNumberIndexPageRoute: typeof sSlug_noteNumberIndexPageRoute
  sSlug_noteNumberEditDotpageRoute: typeof sSlug_noteNumberEditDotpageRoute
  sSlugAttachmentsNewDotpageRoute: typeof sSlugAttachmentsNewDotpageRoute
  sSlugAttachmentsIndexDotpageRoute: typeof sSlugAttachmentsIndexDotpageRoute
  sSlug_noteNumberAttachmentsNewDotpageRoute: typeof sSlug_noteNumberAttachmentsNewDotpageRoute
  sSlug_noteNumberAttachmentsIndexDotpageRoute: typeof sSlug_noteNumberAttachmentsIndexDotpageRoute
}

const authDotlayoutRouteChildren: authDotlayoutRouteChildren = {
  indexPageRoute: indexPageRoute,
  sSlugIndexPageRoute: sSlugIndexPageRoute,
  sSlugNewDotpageRoute: sSlugNewDotpageRoute,
  sSlug_noteNumberIndexPageRoute: sSlug_noteNumberIndexPageRoute,
  sSlug_noteNumberEditDotpageRoute: sSlug_noteNumberEditDotpageRoute,
  sSlugAttachmentsNewDotpageRoute: sSlugAttachmentsNewDotpageRoute,
  sSlugAttachmentsIndexDotpageRoute: sSlugAttachmentsIndexDotpageRoute,
  sSlug_noteNumberAttachmentsNewDotpageRoute:
    sSlug_noteNumberAttachmentsNewDotpageRoute,
  sSlug_noteNumberAttachmentsIndexDotpageRoute:
    sSlug_noteNumberAttachmentsIndexDotpageRoute,
}

const authDotlayoutRouteWithChildren = authDotlayoutRoute._addFileChildren(
  authDotlayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authDotlayoutRoute: authDotlayoutRouteWithChildren,
  loginDotpageRoute: loginDotpageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
