/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpacesIndexRouteImport } from './routes/spaces_/index'
import { Route as NotesIndexRouteImport } from './routes/notes_/index'
import { Route as NotesSpaceIdIndexRouteImport } from './routes/notes_/$spaceId_/index'
import { Route as NotesSpaceIdNewRouteImport } from './routes/notes_/$spaceId_/new'
import { Route as NotesSpaceIdNoteIdRouteImport } from './routes/notes_/$spaceId_/$noteId'
import { Route as SpacesSpaceIdFieldsIndexRouteImport } from './routes/spaces_/$spaceId_/fields_/index'
import { Route as SpacesSpaceIdFieldsNewRouteImport } from './routes/spaces_/$spaceId_/fields_/new'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesIndexRoute = SpacesIndexRouteImport.update({
  id: '/spaces_/',
  path: '/spaces/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/notes_/',
  path: '/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesSpaceIdIndexRoute = NotesSpaceIdIndexRouteImport.update({
  id: '/notes_/$spaceId_/',
  path: '/notes/$spaceId/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesSpaceIdNewRoute = NotesSpaceIdNewRouteImport.update({
  id: '/notes_/$spaceId_/new',
  path: '/notes/$spaceId/new',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesSpaceIdNoteIdRoute = NotesSpaceIdNoteIdRouteImport.update({
  id: '/notes_/$spaceId_/$noteId',
  path: '/notes/$spaceId/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesSpaceIdFieldsIndexRoute =
  SpacesSpaceIdFieldsIndexRouteImport.update({
    id: '/spaces_/$spaceId_/fields_/',
    path: '/spaces/$spaceId/fields/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SpacesSpaceIdFieldsNewRoute = SpacesSpaceIdFieldsNewRouteImport.update({
  id: '/spaces_/$spaceId_/fields_/new',
  path: '/spaces/$spaceId/fields/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesIndexRoute
  '/spaces': typeof SpacesIndexRoute
  '/notes/$spaceId/$noteId': typeof NotesSpaceIdNoteIdRoute
  '/notes/$spaceId/new': typeof NotesSpaceIdNewRoute
  '/notes/$spaceId': typeof NotesSpaceIdIndexRoute
  '/spaces/$spaceId/fields/new': typeof SpacesSpaceIdFieldsNewRoute
  '/spaces/$spaceId/fields': typeof SpacesSpaceIdFieldsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesIndexRoute
  '/spaces': typeof SpacesIndexRoute
  '/notes/$spaceId/$noteId': typeof NotesSpaceIdNoteIdRoute
  '/notes/$spaceId/new': typeof NotesSpaceIdNewRoute
  '/notes/$spaceId': typeof NotesSpaceIdIndexRoute
  '/spaces/$spaceId/fields/new': typeof SpacesSpaceIdFieldsNewRoute
  '/spaces/$spaceId/fields': typeof SpacesSpaceIdFieldsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notes_/': typeof NotesIndexRoute
  '/spaces_/': typeof SpacesIndexRoute
  '/notes_/$spaceId_/$noteId': typeof NotesSpaceIdNoteIdRoute
  '/notes_/$spaceId_/new': typeof NotesSpaceIdNewRoute
  '/notes_/$spaceId_/': typeof NotesSpaceIdIndexRoute
  '/spaces_/$spaceId_/fields_/new': typeof SpacesSpaceIdFieldsNewRoute
  '/spaces_/$spaceId_/fields_/': typeof SpacesSpaceIdFieldsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/notes'
    | '/spaces'
    | '/notes/$spaceId/$noteId'
    | '/notes/$spaceId/new'
    | '/notes/$spaceId'
    | '/spaces/$spaceId/fields/new'
    | '/spaces/$spaceId/fields'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/notes'
    | '/spaces'
    | '/notes/$spaceId/$noteId'
    | '/notes/$spaceId/new'
    | '/notes/$spaceId'
    | '/spaces/$spaceId/fields/new'
    | '/spaces/$spaceId/fields'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/notes_/'
    | '/spaces_/'
    | '/notes_/$spaceId_/$noteId'
    | '/notes_/$spaceId_/new'
    | '/notes_/$spaceId_/'
    | '/spaces_/$spaceId_/fields_/new'
    | '/spaces_/$spaceId_/fields_/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  NotesIndexRoute: typeof NotesIndexRoute
  SpacesIndexRoute: typeof SpacesIndexRoute
  NotesSpaceIdNoteIdRoute: typeof NotesSpaceIdNoteIdRoute
  NotesSpaceIdNewRoute: typeof NotesSpaceIdNewRoute
  NotesSpaceIdIndexRoute: typeof NotesSpaceIdIndexRoute
  SpacesSpaceIdFieldsNewRoute: typeof SpacesSpaceIdFieldsNewRoute
  SpacesSpaceIdFieldsIndexRoute: typeof SpacesSpaceIdFieldsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces_/': {
      id: '/spaces_/'
      path: '/spaces'
      fullPath: '/spaces'
      preLoaderRoute: typeof SpacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes_/': {
      id: '/notes_/'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes_/$spaceId_/': {
      id: '/notes_/$spaceId_/'
      path: '/notes/$spaceId'
      fullPath: '/notes/$spaceId'
      preLoaderRoute: typeof NotesSpaceIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes_/$spaceId_/new': {
      id: '/notes_/$spaceId_/new'
      path: '/notes/$spaceId/new'
      fullPath: '/notes/$spaceId/new'
      preLoaderRoute: typeof NotesSpaceIdNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes_/$spaceId_/$noteId': {
      id: '/notes_/$spaceId_/$noteId'
      path: '/notes/$spaceId/$noteId'
      fullPath: '/notes/$spaceId/$noteId'
      preLoaderRoute: typeof NotesSpaceIdNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces_/$spaceId_/fields_/': {
      id: '/spaces_/$spaceId_/fields_/'
      path: '/spaces/$spaceId/fields'
      fullPath: '/spaces/$spaceId/fields'
      preLoaderRoute: typeof SpacesSpaceIdFieldsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces_/$spaceId_/fields_/new': {
      id: '/spaces_/$spaceId_/fields_/new'
      path: '/spaces/$spaceId/fields/new'
      fullPath: '/spaces/$spaceId/fields/new'
      preLoaderRoute: typeof SpacesSpaceIdFieldsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  NotesIndexRoute: NotesIndexRoute,
  SpacesIndexRoute: SpacesIndexRoute,
  NotesSpaceIdNoteIdRoute: NotesSpaceIdNoteIdRoute,
  NotesSpaceIdNewRoute: NotesSpaceIdNewRoute,
  NotesSpaceIdIndexRoute: NotesSpaceIdIndexRoute,
  SpacesSpaceIdFieldsNewRoute: SpacesSpaceIdFieldsNewRoute,
  SpacesSpaceIdFieldsIndexRoute: SpacesSpaceIdFieldsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
