/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/root.layout'
import { Route as loginDotpageRouteImport } from './routes/login.page'
import { Route as authDotlayoutRouteImport } from './routes/auth.layout'
import { Route as spacesLayoutRouteImport } from './routes/spaces/layout'
import { Route as adminLayoutRouteImport } from './routes/admin/layout'
import { Route as indexDotpageRouteImport } from './routes/index.page'
import { Route as adminUsersIndexDotpageRouteImport } from './routes/admin/users/index.page'
import { Route as sSlugNewDotpageRouteImport } from './routes/s/_slug_/new.page'
import { Route as spacesNewDotpageRouteImport } from './routes/spaces/new.page'
import { Route as spacesImportDotpageRouteImport } from './routes/spaces/import.page'
import { Route as adminTempSpaceAccessDotpageRouteImport } from './routes/admin/temp-space-access.page'
import { Route as adminPendingAttachmentsPageRouteImport } from './routes/admin/pending-attachments/page'
import { Route as adminBackupsDotpageRouteImport } from './routes/admin/backups.page'
import { Route as sSlugIndexPageRouteImport } from './routes/s/_slug_/index/page'
import { Route as sSlugAttachmentsIndexDotpageRouteImport } from './routes/s/_slug_/attachments/index.page'
import { Route as sSlugAttachmentsNewDotpageRouteImport } from './routes/s/_slug_/attachments/new.page'
import { Route as sSlug_noteNumberEditDotpageRouteImport } from './routes/s/_slug_/_noteNumber_/edit.page'
import { Route as spacesSlugTemplatesPageRouteImport } from './routes/spaces/_slug_/templates/page'
import { Route as spacesSlugSettingsPageRouteImport } from './routes/spaces/_slug_/settings/page'
import { Route as spacesSlugMembersDotpageRouteImport } from './routes/spaces/_slug_/members.page'
import { Route as spacesSlugExportDotpageRouteImport } from './routes/spaces/_slug_/export.page'
import { Route as adminUsersNewDotpageRouteImport } from './routes/admin/users/new.page'
import { Route as adminTelegramTasksDotpageRouteImport } from './routes/admin/telegram/tasks.page'
import { Route as adminTelegramMirrorsDotpageRouteImport } from './routes/admin/telegram/mirrors.page'
import { Route as sSlug_noteNumberIndexPageRouteImport } from './routes/s/_slug_/_noteNumber_/index/page'
import { Route as sSlug_noteNumberAttachmentsIndexDotpageRouteImport } from './routes/s/_slug_/_noteNumber_/attachments/index.page'
import { Route as spacesSlugFiltersIndexDotpageRouteImport } from './routes/spaces/_slug_/filters/index.page'
import { Route as spacesSlugFieldsIndexDotpageRouteImport } from './routes/spaces/_slug_/fields/index.page'
import { Route as sSlug_noteNumberAttachmentsNewDotpageRouteImport } from './routes/s/_slug_/_noteNumber_/attachments/new.page'
import { Route as spacesSlugFiltersNewDotpageRouteImport } from './routes/spaces/_slug_/filters/new.page'
import { Route as spacesSlugFieldsNewDotpageRouteImport } from './routes/spaces/_slug_/fields/new.page'
import { Route as spacesSlugFiltersFilterNameEditDotpageRouteImport } from './routes/spaces/_slug_/filters/_filterName_/edit.page'
import { Route as spacesSlugFieldsFieldNameEditDotpageRouteImport } from './routes/spaces/_slug_/fields/_fieldName_/edit.page'

const loginDotpageRoute = loginDotpageRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authDotlayoutRoute = authDotlayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const spacesLayoutRoute = spacesLayoutRouteImport.update({
  id: '/_spaces',
  getParentRoute: () => authDotlayoutRoute,
} as any)
const adminLayoutRoute = adminLayoutRouteImport.update({
  id: '/_admin',
  getParentRoute: () => authDotlayoutRoute,
} as any)
const indexDotpageRoute = indexDotpageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authDotlayoutRoute,
} as any)
const adminUsersIndexDotpageRoute = adminUsersIndexDotpageRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => adminLayoutRoute,
} as any)
const sSlugNewDotpageRoute = sSlugNewDotpageRouteImport.update({
  id: '/s/$slug/new',
  path: '/s/$slug/new',
  getParentRoute: () => authDotlayoutRoute,
} as any)
const spacesNewDotpageRoute = spacesNewDotpageRouteImport.update({
  id: '/spaces/new',
  path: '/spaces/new',
  getParentRoute: () => spacesLayoutRoute,
} as any)
const spacesImportDotpageRoute = spacesImportDotpageRouteImport.update({
  id: '/spaces/import',
  path: '/spaces/import',
  getParentRoute: () => spacesLayoutRoute,
} as any)
const adminTempSpaceAccessDotpageRoute =
  adminTempSpaceAccessDotpageRouteImport.update({
    id: '/admin/temp-space-access',
    path: '/admin/temp-space-access',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminPendingAttachmentsPageRoute =
  adminPendingAttachmentsPageRouteImport.update({
    id: '/admin/pending-attachments',
    path: '/admin/pending-attachments',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminBackupsDotpageRoute = adminBackupsDotpageRouteImport.update({
  id: '/admin/backups',
  path: '/admin/backups',
  getParentRoute: () => adminLayoutRoute,
} as any)
const sSlugIndexPageRoute = sSlugIndexPageRouteImport.update({
  id: '/s/$slug/',
  path: '/s/$slug/',
  getParentRoute: () => authDotlayoutRoute,
} as any)
const sSlugAttachmentsIndexDotpageRoute =
  sSlugAttachmentsIndexDotpageRouteImport.update({
    id: '/s/$slug/attachments/',
    path: '/s/$slug/attachments/',
    getParentRoute: () => authDotlayoutRoute,
  } as any)
const sSlugAttachmentsNewDotpageRoute =
  sSlugAttachmentsNewDotpageRouteImport.update({
    id: '/s/$slug/attachments/new',
    path: '/s/$slug/attachments/new',
    getParentRoute: () => authDotlayoutRoute,
  } as any)
const sSlug_noteNumberEditDotpageRoute =
  sSlug_noteNumberEditDotpageRouteImport.update({
    id: '/s/$slug/$noteNumber/edit',
    path: '/s/$slug/$noteNumber/edit',
    getParentRoute: () => authDotlayoutRoute,
  } as any)
const spacesSlugTemplatesPageRoute = spacesSlugTemplatesPageRouteImport.update({
  id: '/spaces/$slug/templates',
  path: '/spaces/$slug/templates',
  getParentRoute: () => spacesLayoutRoute,
} as any)
const spacesSlugSettingsPageRoute = spacesSlugSettingsPageRouteImport.update({
  id: '/spaces/$slug/settings',
  path: '/spaces/$slug/settings',
  getParentRoute: () => spacesLayoutRoute,
} as any)
const spacesSlugMembersDotpageRoute =
  spacesSlugMembersDotpageRouteImport.update({
    id: '/spaces/$slug/members',
    path: '/spaces/$slug/members',
    getParentRoute: () => spacesLayoutRoute,
  } as any)
const spacesSlugExportDotpageRoute = spacesSlugExportDotpageRouteImport.update({
  id: '/spaces/$slug/export',
  path: '/spaces/$slug/export',
  getParentRoute: () => spacesLayoutRoute,
} as any)
const adminUsersNewDotpageRoute = adminUsersNewDotpageRouteImport.update({
  id: '/admin/users/new',
  path: '/admin/users/new',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminTelegramTasksDotpageRoute =
  adminTelegramTasksDotpageRouteImport.update({
    id: '/admin/telegram/tasks',
    path: '/admin/telegram/tasks',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminTelegramMirrorsDotpageRoute =
  adminTelegramMirrorsDotpageRouteImport.update({
    id: '/admin/telegram/mirrors',
    path: '/admin/telegram/mirrors',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const sSlug_noteNumberIndexPageRoute =
  sSlug_noteNumberIndexPageRouteImport.update({
    id: '/s/$slug/$noteNumber/',
    path: '/s/$slug/$noteNumber/',
    getParentRoute: () => authDotlayoutRoute,
  } as any)
const sSlug_noteNumberAttachmentsIndexDotpageRoute =
  sSlug_noteNumberAttachmentsIndexDotpageRouteImport.update({
    id: '/s/$slug/$noteNumber/attachments/',
    path: '/s/$slug/$noteNumber/attachments/',
    getParentRoute: () => authDotlayoutRoute,
  } as any)
const spacesSlugFiltersIndexDotpageRoute =
  spacesSlugFiltersIndexDotpageRouteImport.update({
    id: '/spaces/$slug/filters/',
    path: '/spaces/$slug/filters/',
    getParentRoute: () => spacesLayoutRoute,
  } as any)
const spacesSlugFieldsIndexDotpageRoute =
  spacesSlugFieldsIndexDotpageRouteImport.update({
    id: '/spaces/$slug/fields/',
    path: '/spaces/$slug/fields/',
    getParentRoute: () => spacesLayoutRoute,
  } as any)
const sSlug_noteNumberAttachmentsNewDotpageRoute =
  sSlug_noteNumberAttachmentsNewDotpageRouteImport.update({
    id: '/s/$slug/$noteNumber/attachments/new',
    path: '/s/$slug/$noteNumber/attachments/new',
    getParentRoute: () => authDotlayoutRoute,
  } as any)
const spacesSlugFiltersNewDotpageRoute =
  spacesSlugFiltersNewDotpageRouteImport.update({
    id: '/spaces/$slug/filters/new',
    path: '/spaces/$slug/filters/new',
    getParentRoute: () => spacesLayoutRoute,
  } as any)
const spacesSlugFieldsNewDotpageRoute =
  spacesSlugFieldsNewDotpageRouteImport.update({
    id: '/spaces/$slug/fields/new',
    path: '/spaces/$slug/fields/new',
    getParentRoute: () => spacesLayoutRoute,
  } as any)
const spacesSlugFiltersFilterNameEditDotpageRoute =
  spacesSlugFiltersFilterNameEditDotpageRouteImport.update({
    id: '/spaces/$slug/filters/$filterName/edit',
    path: '/spaces/$slug/filters/$filterName/edit',
    getParentRoute: () => spacesLayoutRoute,
  } as any)
const spacesSlugFieldsFieldNameEditDotpageRoute =
  spacesSlugFieldsFieldNameEditDotpageRouteImport.update({
    id: '/spaces/$slug/fields/$fieldName/edit',
    path: '/spaces/$slug/fields/$fieldName/edit',
    getParentRoute: () => spacesLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof indexDotpageRoute
  '/login': typeof loginDotpageRoute
  '/s/$slug/': typeof sSlugIndexPageRoute
  '/admin/backups': typeof adminBackupsDotpageRoute
  '/admin/pending-attachments': typeof adminPendingAttachmentsPageRoute
  '/admin/temp-space-access': typeof adminTempSpaceAccessDotpageRoute
  '/spaces/import': typeof spacesImportDotpageRoute
  '/spaces/new': typeof spacesNewDotpageRoute
  '/s/$slug/new': typeof sSlugNewDotpageRoute
  '/admin/users': typeof adminUsersIndexDotpageRoute
  '/s/$slug/$noteNumber/': typeof sSlug_noteNumberIndexPageRoute
  '/admin/telegram/mirrors': typeof adminTelegramMirrorsDotpageRoute
  '/admin/telegram/tasks': typeof adminTelegramTasksDotpageRoute
  '/admin/users/new': typeof adminUsersNewDotpageRoute
  '/spaces/$slug/export': typeof spacesSlugExportDotpageRoute
  '/spaces/$slug/members': typeof spacesSlugMembersDotpageRoute
  '/spaces/$slug/settings': typeof spacesSlugSettingsPageRoute
  '/spaces/$slug/templates': typeof spacesSlugTemplatesPageRoute
  '/s/$slug/$noteNumber/edit': typeof sSlug_noteNumberEditDotpageRoute
  '/s/$slug/attachments/new': typeof sSlugAttachmentsNewDotpageRoute
  '/s/$slug/attachments/': typeof sSlugAttachmentsIndexDotpageRoute
  '/spaces/$slug/fields/new': typeof spacesSlugFieldsNewDotpageRoute
  '/spaces/$slug/filters/new': typeof spacesSlugFiltersNewDotpageRoute
  '/s/$slug/$noteNumber/attachments/new': typeof sSlug_noteNumberAttachmentsNewDotpageRoute
  '/spaces/$slug/fields/': typeof spacesSlugFieldsIndexDotpageRoute
  '/spaces/$slug/filters/': typeof spacesSlugFiltersIndexDotpageRoute
  '/s/$slug/$noteNumber/attachments/': typeof sSlug_noteNumberAttachmentsIndexDotpageRoute
  '/spaces/$slug/fields/$fieldName/edit': typeof spacesSlugFieldsFieldNameEditDotpageRoute
  '/spaces/$slug/filters/$filterName/edit': typeof spacesSlugFiltersFilterNameEditDotpageRoute
}
export interface FileRoutesByTo {
  '/login': typeof loginDotpageRoute
  '/': typeof indexDotpageRoute
  '/s/$slug': typeof sSlugIndexPageRoute
  '/admin/backups': typeof adminBackupsDotpageRoute
  '/admin/pending-attachments': typeof adminPendingAttachmentsPageRoute
  '/admin/temp-space-access': typeof adminTempSpaceAccessDotpageRoute
  '/spaces/import': typeof spacesImportDotpageRoute
  '/spaces/new': typeof spacesNewDotpageRoute
  '/s/$slug/new': typeof sSlugNewDotpageRoute
  '/admin/users': typeof adminUsersIndexDotpageRoute
  '/s/$slug/$noteNumber': typeof sSlug_noteNumberIndexPageRoute
  '/admin/telegram/mirrors': typeof adminTelegramMirrorsDotpageRoute
  '/admin/telegram/tasks': typeof adminTelegramTasksDotpageRoute
  '/admin/users/new': typeof adminUsersNewDotpageRoute
  '/spaces/$slug/export': typeof spacesSlugExportDotpageRoute
  '/spaces/$slug/members': typeof spacesSlugMembersDotpageRoute
  '/spaces/$slug/settings': typeof spacesSlugSettingsPageRoute
  '/spaces/$slug/templates': typeof spacesSlugTemplatesPageRoute
  '/s/$slug/$noteNumber/edit': typeof sSlug_noteNumberEditDotpageRoute
  '/s/$slug/attachments/new': typeof sSlugAttachmentsNewDotpageRoute
  '/s/$slug/attachments': typeof sSlugAttachmentsIndexDotpageRoute
  '/spaces/$slug/fields/new': typeof spacesSlugFieldsNewDotpageRoute
  '/spaces/$slug/filters/new': typeof spacesSlugFiltersNewDotpageRoute
  '/s/$slug/$noteNumber/attachments/new': typeof sSlug_noteNumberAttachmentsNewDotpageRoute
  '/spaces/$slug/fields': typeof spacesSlugFieldsIndexDotpageRoute
  '/spaces/$slug/filters': typeof spacesSlugFiltersIndexDotpageRoute
  '/s/$slug/$noteNumber/attachments': typeof sSlug_noteNumberAttachmentsIndexDotpageRoute
  '/spaces/$slug/fields/$fieldName/edit': typeof spacesSlugFieldsFieldNameEditDotpageRoute
  '/spaces/$slug/filters/$filterName/edit': typeof spacesSlugFiltersFilterNameEditDotpageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof authDotlayoutRouteWithChildren
  '/login': typeof loginDotpageRoute
  '/_auth/': typeof indexDotpageRoute
  '/_auth/_admin': typeof adminLayoutRouteWithChildren
  '/_auth/_spaces': typeof spacesLayoutRouteWithChildren
  '/_auth/s/$slug/': typeof sSlugIndexPageRoute
  '/_auth/_admin/admin/backups': typeof adminBackupsDotpageRoute
  '/_auth/_admin/admin/pending-attachments': typeof adminPendingAttachmentsPageRoute
  '/_auth/_admin/admin/temp-space-access': typeof adminTempSpaceAccessDotpageRoute
  '/_auth/_spaces/spaces/import': typeof spacesImportDotpageRoute
  '/_auth/_spaces/spaces/new': typeof spacesNewDotpageRoute
  '/_auth/s/$slug/new': typeof sSlugNewDotpageRoute
  '/_auth/_admin/admin/users': typeof adminUsersIndexDotpageRoute
  '/_auth/s/$slug/$noteNumber/': typeof sSlug_noteNumberIndexPageRoute
  '/_auth/_admin/admin/telegram/mirrors': typeof adminTelegramMirrorsDotpageRoute
  '/_auth/_admin/admin/telegram/tasks': typeof adminTelegramTasksDotpageRoute
  '/_auth/_admin/admin/users/new': typeof adminUsersNewDotpageRoute
  '/_auth/_spaces/spaces/$slug/export': typeof spacesSlugExportDotpageRoute
  '/_auth/_spaces/spaces/$slug/members': typeof spacesSlugMembersDotpageRoute
  '/_auth/_spaces/spaces/$slug/settings': typeof spacesSlugSettingsPageRoute
  '/_auth/_spaces/spaces/$slug/templates': typeof spacesSlugTemplatesPageRoute
  '/_auth/s/$slug/$noteNumber/edit': typeof sSlug_noteNumberEditDotpageRoute
  '/_auth/s/$slug/attachments/new': typeof sSlugAttachmentsNewDotpageRoute
  '/_auth/s/$slug/attachments/': typeof sSlugAttachmentsIndexDotpageRoute
  '/_auth/_spaces/spaces/$slug/fields/new': typeof spacesSlugFieldsNewDotpageRoute
  '/_auth/_spaces/spaces/$slug/filters/new': typeof spacesSlugFiltersNewDotpageRoute
  '/_auth/s/$slug/$noteNumber/attachments/new': typeof sSlug_noteNumberAttachmentsNewDotpageRoute
  '/_auth/_spaces/spaces/$slug/fields/': typeof spacesSlugFieldsIndexDotpageRoute
  '/_auth/_spaces/spaces/$slug/filters/': typeof spacesSlugFiltersIndexDotpageRoute
  '/_auth/s/$slug/$noteNumber/attachments/': typeof sSlug_noteNumberAttachmentsIndexDotpageRoute
  '/_auth/_spaces/spaces/$slug/fields/$fieldName/edit': typeof spacesSlugFieldsFieldNameEditDotpageRoute
  '/_auth/_spaces/spaces/$slug/filters/$filterName/edit': typeof spacesSlugFiltersFilterNameEditDotpageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/s/$slug/'
    | '/admin/backups'
    | '/admin/pending-attachments'
    | '/admin/temp-space-access'
    | '/spaces/import'
    | '/spaces/new'
    | '/s/$slug/new'
    | '/admin/users'
    | '/s/$slug/$noteNumber/'
    | '/admin/telegram/mirrors'
    | '/admin/telegram/tasks'
    | '/admin/users/new'
    | '/spaces/$slug/export'
    | '/spaces/$slug/members'
    | '/spaces/$slug/settings'
    | '/spaces/$slug/templates'
    | '/s/$slug/$noteNumber/edit'
    | '/s/$slug/attachments/new'
    | '/s/$slug/attachments/'
    | '/spaces/$slug/fields/new'
    | '/spaces/$slug/filters/new'
    | '/s/$slug/$noteNumber/attachments/new'
    | '/spaces/$slug/fields/'
    | '/spaces/$slug/filters/'
    | '/s/$slug/$noteNumber/attachments/'
    | '/spaces/$slug/fields/$fieldName/edit'
    | '/spaces/$slug/filters/$filterName/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/s/$slug'
    | '/admin/backups'
    | '/admin/pending-attachments'
    | '/admin/temp-space-access'
    | '/spaces/import'
    | '/spaces/new'
    | '/s/$slug/new'
    | '/admin/users'
    | '/s/$slug/$noteNumber'
    | '/admin/telegram/mirrors'
    | '/admin/telegram/tasks'
    | '/admin/users/new'
    | '/spaces/$slug/export'
    | '/spaces/$slug/members'
    | '/spaces/$slug/settings'
    | '/spaces/$slug/templates'
    | '/s/$slug/$noteNumber/edit'
    | '/s/$slug/attachments/new'
    | '/s/$slug/attachments'
    | '/spaces/$slug/fields/new'
    | '/spaces/$slug/filters/new'
    | '/s/$slug/$noteNumber/attachments/new'
    | '/spaces/$slug/fields'
    | '/spaces/$slug/filters'
    | '/s/$slug/$noteNumber/attachments'
    | '/spaces/$slug/fields/$fieldName/edit'
    | '/spaces/$slug/filters/$filterName/edit'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/'
    | '/_auth/_admin'
    | '/_auth/_spaces'
    | '/_auth/s/$slug/'
    | '/_auth/_admin/admin/backups'
    | '/_auth/_admin/admin/pending-attachments'
    | '/_auth/_admin/admin/temp-space-access'
    | '/_auth/_spaces/spaces/import'
    | '/_auth/_spaces/spaces/new'
    | '/_auth/s/$slug/new'
    | '/_auth/_admin/admin/users'
    | '/_auth/s/$slug/$noteNumber/'
    | '/_auth/_admin/admin/telegram/mirrors'
    | '/_auth/_admin/admin/telegram/tasks'
    | '/_auth/_admin/admin/users/new'
    | '/_auth/_spaces/spaces/$slug/export'
    | '/_auth/_spaces/spaces/$slug/members'
    | '/_auth/_spaces/spaces/$slug/settings'
    | '/_auth/_spaces/spaces/$slug/templates'
    | '/_auth/s/$slug/$noteNumber/edit'
    | '/_auth/s/$slug/attachments/new'
    | '/_auth/s/$slug/attachments/'
    | '/_auth/_spaces/spaces/$slug/fields/new'
    | '/_auth/_spaces/spaces/$slug/filters/new'
    | '/_auth/s/$slug/$noteNumber/attachments/new'
    | '/_auth/_spaces/spaces/$slug/fields/'
    | '/_auth/_spaces/spaces/$slug/filters/'
    | '/_auth/s/$slug/$noteNumber/attachments/'
    | '/_auth/_spaces/spaces/$slug/fields/$fieldName/edit'
    | '/_auth/_spaces/spaces/$slug/filters/$filterName/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authDotlayoutRoute: typeof authDotlayoutRouteWithChildren
  loginDotpageRoute: typeof loginDotpageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof loginDotpageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof authDotlayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_spaces': {
      id: '/_auth/_spaces'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof spacesLayoutRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth/_admin': {
      id: '/_auth/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof adminLayoutRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexDotpageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth/_admin/admin/users': {
      id: '/_auth/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof adminUsersIndexDotpageRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/_auth/s/$slug/new': {
      id: '/_auth/s/$slug/new'
      path: '/s/$slug/new'
      fullPath: '/s/$slug/new'
      preLoaderRoute: typeof sSlugNewDotpageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth/_spaces/spaces/new': {
      id: '/_auth/_spaces/spaces/new'
      path: '/spaces/new'
      fullPath: '/spaces/new'
      preLoaderRoute: typeof spacesNewDotpageRouteImport
      parentRoute: typeof spacesLayoutRoute
    }
    '/_auth/_spaces/spaces/import': {
      id: '/_auth/_spaces/spaces/import'
      path: '/spaces/import'
      fullPath: '/spaces/import'
      preLoaderRoute: typeof spacesImportDotpageRouteImport
      parentRoute: typeof spacesLayoutRoute
    }
    '/_auth/_admin/admin/temp-space-access': {
      id: '/_auth/_admin/admin/temp-space-access'
      path: '/admin/temp-space-access'
      fullPath: '/admin/temp-space-access'
      preLoaderRoute: typeof adminTempSpaceAccessDotpageRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/_auth/_admin/admin/pending-attachments': {
      id: '/_auth/_admin/admin/pending-attachments'
      path: '/admin/pending-attachments'
      fullPath: '/admin/pending-attachments'
      preLoaderRoute: typeof adminPendingAttachmentsPageRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/_auth/_admin/admin/backups': {
      id: '/_auth/_admin/admin/backups'
      path: '/admin/backups'
      fullPath: '/admin/backups'
      preLoaderRoute: typeof adminBackupsDotpageRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/_auth/s/$slug/': {
      id: '/_auth/s/$slug/'
      path: '/s/$slug'
      fullPath: '/s/$slug/'
      preLoaderRoute: typeof sSlugIndexPageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth/s/$slug/attachments/': {
      id: '/_auth/s/$slug/attachments/'
      path: '/s/$slug/attachments'
      fullPath: '/s/$slug/attachments/'
      preLoaderRoute: typeof sSlugAttachmentsIndexDotpageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth/s/$slug/attachments/new': {
      id: '/_auth/s/$slug/attachments/new'
      path: '/s/$slug/attachments/new'
      fullPath: '/s/$slug/attachments/new'
      preLoaderRoute: typeof sSlugAttachmentsNewDotpageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth/s/$slug/$noteNumber/edit': {
      id: '/_auth/s/$slug/$noteNumber/edit'
      path: '/s/$slug/$noteNumber/edit'
      fullPath: '/s/$slug/$noteNumber/edit'
      preLoaderRoute: typeof sSlug_noteNumberEditDotpageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth/_spaces/spaces/$slug/templates': {
      id: '/_auth/_spaces/spaces/$slug/templates'
      path: '/spaces/$slug/templates'
      fullPath: '/spaces/$slug/templates'
      preLoaderRoute: typeof spacesSlugTemplatesPageRouteImport
      parentRoute: typeof spacesLayoutRoute
    }
    '/_auth/_spaces/spaces/$slug/settings': {
      id: '/_auth/_spaces/spaces/$slug/settings'
      path: '/spaces/$slug/settings'
      fullPath: '/spaces/$slug/settings'
      preLoaderRoute: typeof spacesSlugSettingsPageRouteImport
      parentRoute: typeof spacesLayoutRoute
    }
    '/_auth/_spaces/spaces/$slug/members': {
      id: '/_auth/_spaces/spaces/$slug/members'
      path: '/spaces/$slug/members'
      fullPath: '/spaces/$slug/members'
      preLoaderRoute: typeof spacesSlugMembersDotpageRouteImport
      parentRoute: typeof spacesLayoutRoute
    }
    '/_auth/_spaces/spaces/$slug/export': {
      id: '/_auth/_spaces/spaces/$slug/export'
      path: '/spaces/$slug/export'
      fullPath: '/spaces/$slug/export'
      preLoaderRoute: typeof spacesSlugExportDotpageRouteImport
      parentRoute: typeof spacesLayoutRoute
    }
    '/_auth/_admin/admin/users/new': {
      id: '/_auth/_admin/admin/users/new'
      path: '/admin/users/new'
      fullPath: '/admin/users/new'
      preLoaderRoute: typeof adminUsersNewDotpageRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/_auth/_admin/admin/telegram/tasks': {
      id: '/_auth/_admin/admin/telegram/tasks'
      path: '/admin/telegram/tasks'
      fullPath: '/admin/telegram/tasks'
      preLoaderRoute: typeof adminTelegramTasksDotpageRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/_auth/_admin/admin/telegram/mirrors': {
      id: '/_auth/_admin/admin/telegram/mirrors'
      path: '/admin/telegram/mirrors'
      fullPath: '/admin/telegram/mirrors'
      preLoaderRoute: typeof adminTelegramMirrorsDotpageRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/_auth/s/$slug/$noteNumber/': {
      id: '/_auth/s/$slug/$noteNumber/'
      path: '/s/$slug/$noteNumber'
      fullPath: '/s/$slug/$noteNumber/'
      preLoaderRoute: typeof sSlug_noteNumberIndexPageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth/s/$slug/$noteNumber/attachments/': {
      id: '/_auth/s/$slug/$noteNumber/attachments/'
      path: '/s/$slug/$noteNumber/attachments'
      fullPath: '/s/$slug/$noteNumber/attachments/'
      preLoaderRoute: typeof sSlug_noteNumberAttachmentsIndexDotpageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth/_spaces/spaces/$slug/filters/': {
      id: '/_auth/_spaces/spaces/$slug/filters/'
      path: '/spaces/$slug/filters'
      fullPath: '/spaces/$slug/filters/'
      preLoaderRoute: typeof spacesSlugFiltersIndexDotpageRouteImport
      parentRoute: typeof spacesLayoutRoute
    }
    '/_auth/_spaces/spaces/$slug/fields/': {
      id: '/_auth/_spaces/spaces/$slug/fields/'
      path: '/spaces/$slug/fields'
      fullPath: '/spaces/$slug/fields/'
      preLoaderRoute: typeof spacesSlugFieldsIndexDotpageRouteImport
      parentRoute: typeof spacesLayoutRoute
    }
    '/_auth/s/$slug/$noteNumber/attachments/new': {
      id: '/_auth/s/$slug/$noteNumber/attachments/new'
      path: '/s/$slug/$noteNumber/attachments/new'
      fullPath: '/s/$slug/$noteNumber/attachments/new'
      preLoaderRoute: typeof sSlug_noteNumberAttachmentsNewDotpageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth/_spaces/spaces/$slug/filters/new': {
      id: '/_auth/_spaces/spaces/$slug/filters/new'
      path: '/spaces/$slug/filters/new'
      fullPath: '/spaces/$slug/filters/new'
      preLoaderRoute: typeof spacesSlugFiltersNewDotpageRouteImport
      parentRoute: typeof spacesLayoutRoute
    }
    '/_auth/_spaces/spaces/$slug/fields/new': {
      id: '/_auth/_spaces/spaces/$slug/fields/new'
      path: '/spaces/$slug/fields/new'
      fullPath: '/spaces/$slug/fields/new'
      preLoaderRoute: typeof spacesSlugFieldsNewDotpageRouteImport
      parentRoute: typeof spacesLayoutRoute
    }
    '/_auth/_spaces/spaces/$slug/filters/$filterName/edit': {
      id: '/_auth/_spaces/spaces/$slug/filters/$filterName/edit'
      path: '/spaces/$slug/filters/$filterName/edit'
      fullPath: '/spaces/$slug/filters/$filterName/edit'
      preLoaderRoute: typeof spacesSlugFiltersFilterNameEditDotpageRouteImport
      parentRoute: typeof spacesLayoutRoute
    }
    '/_auth/_spaces/spaces/$slug/fields/$fieldName/edit': {
      id: '/_auth/_spaces/spaces/$slug/fields/$fieldName/edit'
      path: '/spaces/$slug/fields/$fieldName/edit'
      fullPath: '/spaces/$slug/fields/$fieldName/edit'
      preLoaderRoute: typeof spacesSlugFieldsFieldNameEditDotpageRouteImport
      parentRoute: typeof spacesLayoutRoute
    }
  }
}

interface adminLayoutRouteChildren {
  adminBackupsDotpageRoute: typeof adminBackupsDotpageRoute
  adminPendingAttachmentsPageRoute: typeof adminPendingAttachmentsPageRoute
  adminTempSpaceAccessDotpageRoute: typeof adminTempSpaceAccessDotpageRoute
  adminUsersIndexDotpageRoute: typeof adminUsersIndexDotpageRoute
  adminTelegramMirrorsDotpageRoute: typeof adminTelegramMirrorsDotpageRoute
  adminTelegramTasksDotpageRoute: typeof adminTelegramTasksDotpageRoute
  adminUsersNewDotpageRoute: typeof adminUsersNewDotpageRoute
}

const adminLayoutRouteChildren: adminLayoutRouteChildren = {
  adminBackupsDotpageRoute: adminBackupsDotpageRoute,
  adminPendingAttachmentsPageRoute: adminPendingAttachmentsPageRoute,
  adminTempSpaceAccessDotpageRoute: adminTempSpaceAccessDotpageRoute,
  adminUsersIndexDotpageRoute: adminUsersIndexDotpageRoute,
  adminTelegramMirrorsDotpageRoute: adminTelegramMirrorsDotpageRoute,
  adminTelegramTasksDotpageRoute: adminTelegramTasksDotpageRoute,
  adminUsersNewDotpageRoute: adminUsersNewDotpageRoute,
}

const adminLayoutRouteWithChildren = adminLayoutRoute._addFileChildren(
  adminLayoutRouteChildren,
)

interface spacesLayoutRouteChildren {
  spacesImportDotpageRoute: typeof spacesImportDotpageRoute
  spacesNewDotpageRoute: typeof spacesNewDotpageRoute
  spacesSlugExportDotpageRoute: typeof spacesSlugExportDotpageRoute
  spacesSlugMembersDotpageRoute: typeof spacesSlugMembersDotpageRoute
  spacesSlugSettingsPageRoute: typeof spacesSlugSettingsPageRoute
  spacesSlugTemplatesPageRoute: typeof spacesSlugTemplatesPageRoute
  spacesSlugFieldsNewDotpageRoute: typeof spacesSlugFieldsNewDotpageRoute
  spacesSlugFiltersNewDotpageRoute: typeof spacesSlugFiltersNewDotpageRoute
  spacesSlugFieldsIndexDotpageRoute: typeof spacesSlugFieldsIndexDotpageRoute
  spacesSlugFiltersIndexDotpageRoute: typeof spacesSlugFiltersIndexDotpageRoute
  spacesSlugFieldsFieldNameEditDotpageRoute: typeof spacesSlugFieldsFieldNameEditDotpageRoute
  spacesSlugFiltersFilterNameEditDotpageRoute: typeof spacesSlugFiltersFilterNameEditDotpageRoute
}

const spacesLayoutRouteChildren: spacesLayoutRouteChildren = {
  spacesImportDotpageRoute: spacesImportDotpageRoute,
  spacesNewDotpageRoute: spacesNewDotpageRoute,
  spacesSlugExportDotpageRoute: spacesSlugExportDotpageRoute,
  spacesSlugMembersDotpageRoute: spacesSlugMembersDotpageRoute,
  spacesSlugSettingsPageRoute: spacesSlugSettingsPageRoute,
  spacesSlugTemplatesPageRoute: spacesSlugTemplatesPageRoute,
  spacesSlugFieldsNewDotpageRoute: spacesSlugFieldsNewDotpageRoute,
  spacesSlugFiltersNewDotpageRoute: spacesSlugFiltersNewDotpageRoute,
  spacesSlugFieldsIndexDotpageRoute: spacesSlugFieldsIndexDotpageRoute,
  spacesSlugFiltersIndexDotpageRoute: spacesSlugFiltersIndexDotpageRoute,
  spacesSlugFieldsFieldNameEditDotpageRoute:
    spacesSlugFieldsFieldNameEditDotpageRoute,
  spacesSlugFiltersFilterNameEditDotpageRoute:
    spacesSlugFiltersFilterNameEditDotpageRoute,
}

const spacesLayoutRouteWithChildren = spacesLayoutRoute._addFileChildren(
  spacesLayoutRouteChildren,
)

interface authDotlayoutRouteChildren {
  indexDotpageRoute: typeof indexDotpageRoute
  adminLayoutRoute: typeof adminLayoutRouteWithChildren
  spacesLayoutRoute: typeof spacesLayoutRouteWithChildren
  sSlugIndexPageRoute: typeof sSlugIndexPageRoute
  sSlugNewDotpageRoute: typeof sSlugNewDotpageRoute
  sSlug_noteNumberIndexPageRoute: typeof sSlug_noteNumberIndexPageRoute
  sSlug_noteNumberEditDotpageRoute: typeof sSlug_noteNumberEditDotpageRoute
  sSlugAttachmentsNewDotpageRoute: typeof sSlugAttachmentsNewDotpageRoute
  sSlugAttachmentsIndexDotpageRoute: typeof sSlugAttachmentsIndexDotpageRoute
  sSlug_noteNumberAttachmentsNewDotpageRoute: typeof sSlug_noteNumberAttachmentsNewDotpageRoute
  sSlug_noteNumberAttachmentsIndexDotpageRoute: typeof sSlug_noteNumberAttachmentsIndexDotpageRoute
}

const authDotlayoutRouteChildren: authDotlayoutRouteChildren = {
  indexDotpageRoute: indexDotpageRoute,
  adminLayoutRoute: adminLayoutRouteWithChildren,
  spacesLayoutRoute: spacesLayoutRouteWithChildren,
  sSlugIndexPageRoute: sSlugIndexPageRoute,
  sSlugNewDotpageRoute: sSlugNewDotpageRoute,
  sSlug_noteNumberIndexPageRoute: sSlug_noteNumberIndexPageRoute,
  sSlug_noteNumberEditDotpageRoute: sSlug_noteNumberEditDotpageRoute,
  sSlugAttachmentsNewDotpageRoute: sSlugAttachmentsNewDotpageRoute,
  sSlugAttachmentsIndexDotpageRoute: sSlugAttachmentsIndexDotpageRoute,
  sSlug_noteNumberAttachmentsNewDotpageRoute:
    sSlug_noteNumberAttachmentsNewDotpageRoute,
  sSlug_noteNumberAttachmentsIndexDotpageRoute:
    sSlug_noteNumberAttachmentsIndexDotpageRoute,
}

const authDotlayoutRouteWithChildren = authDotlayoutRoute._addFileChildren(
  authDotlayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authDotlayoutRoute: authDotlayoutRouteWithChildren,
  loginDotpageRoute: loginDotpageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
