/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/root.layout'
import { Route as loginDotpageRouteImport } from './routes/login.page'
import { Route as authDotlayoutRouteImport } from './routes/auth.layout'
import { Route as adminDotlayoutRouteImport } from './routes/admin.layout'
import { Route as indexPageRouteImport } from './routes/index/page'
import { Route as sSlugNewDotpageRouteImport } from './routes/s/_slug_/new.page'
import { Route as adminUsersIndexPageRouteImport } from './routes/admin/users/index/page'
import { Route as adminPendingAttachmentsPageRouteImport } from './routes/admin/pending-attachments/page'
import { Route as sSlugIndexPageRouteImport } from './routes/s/_slug_/index/page'
import { Route as sSlugAttachmentsIndexDotpageRouteImport } from './routes/s/_slug_/attachments/index.page'
import { Route as sSlugAttachmentsNewDotpageRouteImport } from './routes/s/_slug_/attachments/new.page'
import { Route as sSlug_noteNumberEditPageRouteImport } from './routes/s/_slug_/_noteNumber_/edit/page'
import { Route as adminUsersNewDotpageRouteImport } from './routes/admin/users/new.page'
import { Route as adminTelegramTasksPageRouteImport } from './routes/admin/telegram/tasks/page'
import { Route as adminTelegramMirrorsPageRouteImport } from './routes/admin/telegram/mirrors/page'
import { Route as adminSpacesNewDotpageRouteImport } from './routes/admin/spaces/new.page'
import { Route as adminSpacesImportDotpageRouteImport } from './routes/admin/spaces/import.page'
import { Route as sSlug_noteNumberIndexPageRouteImport } from './routes/s/_slug_/_noteNumber_/index/page'
import { Route as adminSpacesIndexPageRouteImport } from './routes/admin/spaces/index/page'
import { Route as sSlug_noteNumberAttachmentsIndexDotpageRouteImport } from './routes/s/_slug_/_noteNumber_/attachments/index.page'
import { Route as sSlug_noteNumberAttachmentsNewDotpageRouteImport } from './routes/s/_slug_/_noteNumber_/attachments/new.page'
import { Route as adminSpacesSlugTemplatesPageRouteImport } from './routes/admin/spaces/_slug_/templates/page'
import { Route as adminSpacesSlugSettingsPageRouteImport } from './routes/admin/spaces/_slug_/settings/page'
import { Route as adminSpacesSlugMembersDotpageRouteImport } from './routes/admin/spaces/_slug_/members.page'
import { Route as adminSpacesSlugExportDotpageRouteImport } from './routes/admin/spaces/_slug_/export.page'
import { Route as adminSpacesSlugFiltersNewDotpageRouteImport } from './routes/admin/spaces/_slug_/filters/new.page'
import { Route as adminSpacesSlugFieldsNewDotpageRouteImport } from './routes/admin/spaces/_slug_/fields/new.page'
import { Route as adminSpacesSlugFiltersIndexPageRouteImport } from './routes/admin/spaces/_slug_/filters/index/page'
import { Route as adminSpacesSlugFieldsIndexPageRouteImport } from './routes/admin/spaces/_slug_/fields/index/page'
import { Route as adminSpacesSlugFiltersFilterNameEditDotpageRouteImport } from './routes/admin/spaces/_slug_/filters/_filterName_/edit.page'
import { Route as adminSpacesSlugFieldsFieldNameEditDotpageRouteImport } from './routes/admin/spaces/_slug_/fields/_fieldName_/edit.page'

const loginDotpageRoute = loginDotpageRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authDotlayoutRoute = authDotlayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const adminDotlayoutRoute = adminDotlayoutRouteImport.update({
  id: '/_admin',
  getParentRoute: () => authDotlayoutRoute,
} as any)
const indexPageRoute = indexPageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authDotlayoutRoute,
} as any)
const sSlugNewDotpageRoute = sSlugNewDotpageRouteImport.update({
  id: '/s/$slug/new',
  path: '/s/$slug/new',
  getParentRoute: () => authDotlayoutRoute,
} as any)
const adminUsersIndexPageRoute = adminUsersIndexPageRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => adminDotlayoutRoute,
} as any)
const adminPendingAttachmentsPageRoute =
  adminPendingAttachmentsPageRouteImport.update({
    id: '/admin/pending-attachments',
    path: '/admin/pending-attachments',
    getParentRoute: () => adminDotlayoutRoute,
  } as any)
const sSlugIndexPageRoute = sSlugIndexPageRouteImport.update({
  id: '/s/$slug/',
  path: '/s/$slug/',
  getParentRoute: () => authDotlayoutRoute,
} as any)
const sSlugAttachmentsIndexDotpageRoute =
  sSlugAttachmentsIndexDotpageRouteImport.update({
    id: '/s/$slug/attachments/',
    path: '/s/$slug/attachments/',
    getParentRoute: () => authDotlayoutRoute,
  } as any)
const sSlugAttachmentsNewDotpageRoute =
  sSlugAttachmentsNewDotpageRouteImport.update({
    id: '/s/$slug/attachments/new',
    path: '/s/$slug/attachments/new',
    getParentRoute: () => authDotlayoutRoute,
  } as any)
const sSlug_noteNumberEditPageRoute =
  sSlug_noteNumberEditPageRouteImport.update({
    id: '/s/$slug/$noteNumber/edit',
    path: '/s/$slug/$noteNumber/edit',
    getParentRoute: () => authDotlayoutRoute,
  } as any)
const adminUsersNewDotpageRoute = adminUsersNewDotpageRouteImport.update({
  id: '/admin/users/new',
  path: '/admin/users/new',
  getParentRoute: () => adminDotlayoutRoute,
} as any)
const adminTelegramTasksPageRoute = adminTelegramTasksPageRouteImport.update({
  id: '/admin/telegram/tasks',
  path: '/admin/telegram/tasks',
  getParentRoute: () => adminDotlayoutRoute,
} as any)
const adminTelegramMirrorsPageRoute =
  adminTelegramMirrorsPageRouteImport.update({
    id: '/admin/telegram/mirrors',
    path: '/admin/telegram/mirrors',
    getParentRoute: () => adminDotlayoutRoute,
  } as any)
const adminSpacesNewDotpageRoute = adminSpacesNewDotpageRouteImport.update({
  id: '/admin/spaces/new',
  path: '/admin/spaces/new',
  getParentRoute: () => adminDotlayoutRoute,
} as any)
const adminSpacesImportDotpageRoute =
  adminSpacesImportDotpageRouteImport.update({
    id: '/admin/spaces/import',
    path: '/admin/spaces/import',
    getParentRoute: () => adminDotlayoutRoute,
  } as any)
const sSlug_noteNumberIndexPageRoute =
  sSlug_noteNumberIndexPageRouteImport.update({
    id: '/s/$slug/$noteNumber/',
    path: '/s/$slug/$noteNumber/',
    getParentRoute: () => authDotlayoutRoute,
  } as any)
const adminSpacesIndexPageRoute = adminSpacesIndexPageRouteImport.update({
  id: '/admin/spaces/',
  path: '/admin/spaces/',
  getParentRoute: () => adminDotlayoutRoute,
} as any)
const sSlug_noteNumberAttachmentsIndexDotpageRoute =
  sSlug_noteNumberAttachmentsIndexDotpageRouteImport.update({
    id: '/s/$slug/$noteNumber/attachments/',
    path: '/s/$slug/$noteNumber/attachments/',
    getParentRoute: () => authDotlayoutRoute,
  } as any)
const sSlug_noteNumberAttachmentsNewDotpageRoute =
  sSlug_noteNumberAttachmentsNewDotpageRouteImport.update({
    id: '/s/$slug/$noteNumber/attachments/new',
    path: '/s/$slug/$noteNumber/attachments/new',
    getParentRoute: () => authDotlayoutRoute,
  } as any)
const adminSpacesSlugTemplatesPageRoute =
  adminSpacesSlugTemplatesPageRouteImport.update({
    id: '/admin/spaces/$slug/templates',
    path: '/admin/spaces/$slug/templates',
    getParentRoute: () => adminDotlayoutRoute,
  } as any)
const adminSpacesSlugSettingsPageRoute =
  adminSpacesSlugSettingsPageRouteImport.update({
    id: '/admin/spaces/$slug/settings',
    path: '/admin/spaces/$slug/settings',
    getParentRoute: () => adminDotlayoutRoute,
  } as any)
const adminSpacesSlugMembersDotpageRoute =
  adminSpacesSlugMembersDotpageRouteImport.update({
    id: '/admin/spaces/$slug/members',
    path: '/admin/spaces/$slug/members',
    getParentRoute: () => adminDotlayoutRoute,
  } as any)
const adminSpacesSlugExportDotpageRoute =
  adminSpacesSlugExportDotpageRouteImport.update({
    id: '/admin/spaces/$slug/export',
    path: '/admin/spaces/$slug/export',
    getParentRoute: () => adminDotlayoutRoute,
  } as any)
const adminSpacesSlugFiltersNewDotpageRoute =
  adminSpacesSlugFiltersNewDotpageRouteImport.update({
    id: '/admin/spaces/$slug/filters/new',
    path: '/admin/spaces/$slug/filters/new',
    getParentRoute: () => adminDotlayoutRoute,
  } as any)
const adminSpacesSlugFieldsNewDotpageRoute =
  adminSpacesSlugFieldsNewDotpageRouteImport.update({
    id: '/admin/spaces/$slug/fields/new',
    path: '/admin/spaces/$slug/fields/new',
    getParentRoute: () => adminDotlayoutRoute,
  } as any)
const adminSpacesSlugFiltersIndexPageRoute =
  adminSpacesSlugFiltersIndexPageRouteImport.update({
    id: '/admin/spaces/$slug/filters/',
    path: '/admin/spaces/$slug/filters/',
    getParentRoute: () => adminDotlayoutRoute,
  } as any)
const adminSpacesSlugFieldsIndexPageRoute =
  adminSpacesSlugFieldsIndexPageRouteImport.update({
    id: '/admin/spaces/$slug/fields/',
    path: '/admin/spaces/$slug/fields/',
    getParentRoute: () => adminDotlayoutRoute,
  } as any)
const adminSpacesSlugFiltersFilterNameEditDotpageRoute =
  adminSpacesSlugFiltersFilterNameEditDotpageRouteImport.update({
    id: '/admin/spaces/$slug/filters/$filterName/edit',
    path: '/admin/spaces/$slug/filters/$filterName/edit',
    getParentRoute: () => adminDotlayoutRoute,
  } as any)
const adminSpacesSlugFieldsFieldNameEditDotpageRoute =
  adminSpacesSlugFieldsFieldNameEditDotpageRouteImport.update({
    id: '/admin/spaces/$slug/fields/$fieldName/edit',
    path: '/admin/spaces/$slug/fields/$fieldName/edit',
    getParentRoute: () => adminDotlayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof indexPageRoute
  '/login': typeof loginDotpageRoute
  '/s/$slug/': typeof sSlugIndexPageRoute
  '/admin/pending-attachments': typeof adminPendingAttachmentsPageRoute
  '/admin/users': typeof adminUsersIndexPageRoute
  '/s/$slug/new': typeof sSlugNewDotpageRoute
  '/admin/spaces/': typeof adminSpacesIndexPageRoute
  '/s/$slug/$noteNumber/': typeof sSlug_noteNumberIndexPageRoute
  '/admin/spaces/import': typeof adminSpacesImportDotpageRoute
  '/admin/spaces/new': typeof adminSpacesNewDotpageRoute
  '/admin/telegram/mirrors': typeof adminTelegramMirrorsPageRoute
  '/admin/telegram/tasks': typeof adminTelegramTasksPageRoute
  '/admin/users/new': typeof adminUsersNewDotpageRoute
  '/s/$slug/$noteNumber/edit': typeof sSlug_noteNumberEditPageRoute
  '/s/$slug/attachments/new': typeof sSlugAttachmentsNewDotpageRoute
  '/s/$slug/attachments/': typeof sSlugAttachmentsIndexDotpageRoute
  '/admin/spaces/$slug/export': typeof adminSpacesSlugExportDotpageRoute
  '/admin/spaces/$slug/members': typeof adminSpacesSlugMembersDotpageRoute
  '/admin/spaces/$slug/settings': typeof adminSpacesSlugSettingsPageRoute
  '/admin/spaces/$slug/templates': typeof adminSpacesSlugTemplatesPageRoute
  '/s/$slug/$noteNumber/attachments/new': typeof sSlug_noteNumberAttachmentsNewDotpageRoute
  '/s/$slug/$noteNumber/attachments/': typeof sSlug_noteNumberAttachmentsIndexDotpageRoute
  '/admin/spaces/$slug/fields/': typeof adminSpacesSlugFieldsIndexPageRoute
  '/admin/spaces/$slug/filters/': typeof adminSpacesSlugFiltersIndexPageRoute
  '/admin/spaces/$slug/fields/new': typeof adminSpacesSlugFieldsNewDotpageRoute
  '/admin/spaces/$slug/filters/new': typeof adminSpacesSlugFiltersNewDotpageRoute
  '/admin/spaces/$slug/fields/$fieldName/edit': typeof adminSpacesSlugFieldsFieldNameEditDotpageRoute
  '/admin/spaces/$slug/filters/$filterName/edit': typeof adminSpacesSlugFiltersFilterNameEditDotpageRoute
}
export interface FileRoutesByTo {
  '/login': typeof loginDotpageRoute
  '/': typeof indexPageRoute
  '/s/$slug': typeof sSlugIndexPageRoute
  '/admin/pending-attachments': typeof adminPendingAttachmentsPageRoute
  '/admin/users': typeof adminUsersIndexPageRoute
  '/s/$slug/new': typeof sSlugNewDotpageRoute
  '/admin/spaces': typeof adminSpacesIndexPageRoute
  '/s/$slug/$noteNumber': typeof sSlug_noteNumberIndexPageRoute
  '/admin/spaces/import': typeof adminSpacesImportDotpageRoute
  '/admin/spaces/new': typeof adminSpacesNewDotpageRoute
  '/admin/telegram/mirrors': typeof adminTelegramMirrorsPageRoute
  '/admin/telegram/tasks': typeof adminTelegramTasksPageRoute
  '/admin/users/new': typeof adminUsersNewDotpageRoute
  '/s/$slug/$noteNumber/edit': typeof sSlug_noteNumberEditPageRoute
  '/s/$slug/attachments/new': typeof sSlugAttachmentsNewDotpageRoute
  '/s/$slug/attachments': typeof sSlugAttachmentsIndexDotpageRoute
  '/admin/spaces/$slug/export': typeof adminSpacesSlugExportDotpageRoute
  '/admin/spaces/$slug/members': typeof adminSpacesSlugMembersDotpageRoute
  '/admin/spaces/$slug/settings': typeof adminSpacesSlugSettingsPageRoute
  '/admin/spaces/$slug/templates': typeof adminSpacesSlugTemplatesPageRoute
  '/s/$slug/$noteNumber/attachments/new': typeof sSlug_noteNumberAttachmentsNewDotpageRoute
  '/s/$slug/$noteNumber/attachments': typeof sSlug_noteNumberAttachmentsIndexDotpageRoute
  '/admin/spaces/$slug/fields': typeof adminSpacesSlugFieldsIndexPageRoute
  '/admin/spaces/$slug/filters': typeof adminSpacesSlugFiltersIndexPageRoute
  '/admin/spaces/$slug/fields/new': typeof adminSpacesSlugFieldsNewDotpageRoute
  '/admin/spaces/$slug/filters/new': typeof adminSpacesSlugFiltersNewDotpageRoute
  '/admin/spaces/$slug/fields/$fieldName/edit': typeof adminSpacesSlugFieldsFieldNameEditDotpageRoute
  '/admin/spaces/$slug/filters/$filterName/edit': typeof adminSpacesSlugFiltersFilterNameEditDotpageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof authDotlayoutRouteWithChildren
  '/login': typeof loginDotpageRoute
  '/_auth/': typeof indexPageRoute
  '/_auth/_admin': typeof adminDotlayoutRouteWithChildren
  '/_auth/s/$slug/': typeof sSlugIndexPageRoute
  '/_auth/_admin/admin/pending-attachments': typeof adminPendingAttachmentsPageRoute
  '/_auth/_admin/admin/users': typeof adminUsersIndexPageRoute
  '/_auth/s/$slug/new': typeof sSlugNewDotpageRoute
  '/_auth/_admin/admin/spaces/': typeof adminSpacesIndexPageRoute
  '/_auth/s/$slug/$noteNumber/': typeof sSlug_noteNumberIndexPageRoute
  '/_auth/_admin/admin/spaces/import': typeof adminSpacesImportDotpageRoute
  '/_auth/_admin/admin/spaces/new': typeof adminSpacesNewDotpageRoute
  '/_auth/_admin/admin/telegram/mirrors': typeof adminTelegramMirrorsPageRoute
  '/_auth/_admin/admin/telegram/tasks': typeof adminTelegramTasksPageRoute
  '/_auth/_admin/admin/users/new': typeof adminUsersNewDotpageRoute
  '/_auth/s/$slug/$noteNumber/edit': typeof sSlug_noteNumberEditPageRoute
  '/_auth/s/$slug/attachments/new': typeof sSlugAttachmentsNewDotpageRoute
  '/_auth/s/$slug/attachments/': typeof sSlugAttachmentsIndexDotpageRoute
  '/_auth/_admin/admin/spaces/$slug/export': typeof adminSpacesSlugExportDotpageRoute
  '/_auth/_admin/admin/spaces/$slug/members': typeof adminSpacesSlugMembersDotpageRoute
  '/_auth/_admin/admin/spaces/$slug/settings': typeof adminSpacesSlugSettingsPageRoute
  '/_auth/_admin/admin/spaces/$slug/templates': typeof adminSpacesSlugTemplatesPageRoute
  '/_auth/s/$slug/$noteNumber/attachments/new': typeof sSlug_noteNumberAttachmentsNewDotpageRoute
  '/_auth/s/$slug/$noteNumber/attachments/': typeof sSlug_noteNumberAttachmentsIndexDotpageRoute
  '/_auth/_admin/admin/spaces/$slug/fields/': typeof adminSpacesSlugFieldsIndexPageRoute
  '/_auth/_admin/admin/spaces/$slug/filters/': typeof adminSpacesSlugFiltersIndexPageRoute
  '/_auth/_admin/admin/spaces/$slug/fields/new': typeof adminSpacesSlugFieldsNewDotpageRoute
  '/_auth/_admin/admin/spaces/$slug/filters/new': typeof adminSpacesSlugFiltersNewDotpageRoute
  '/_auth/_admin/admin/spaces/$slug/fields/$fieldName/edit': typeof adminSpacesSlugFieldsFieldNameEditDotpageRoute
  '/_auth/_admin/admin/spaces/$slug/filters/$filterName/edit': typeof adminSpacesSlugFiltersFilterNameEditDotpageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/s/$slug/'
    | '/admin/pending-attachments'
    | '/admin/users'
    | '/s/$slug/new'
    | '/admin/spaces/'
    | '/s/$slug/$noteNumber/'
    | '/admin/spaces/import'
    | '/admin/spaces/new'
    | '/admin/telegram/mirrors'
    | '/admin/telegram/tasks'
    | '/admin/users/new'
    | '/s/$slug/$noteNumber/edit'
    | '/s/$slug/attachments/new'
    | '/s/$slug/attachments/'
    | '/admin/spaces/$slug/export'
    | '/admin/spaces/$slug/members'
    | '/admin/spaces/$slug/settings'
    | '/admin/spaces/$slug/templates'
    | '/s/$slug/$noteNumber/attachments/new'
    | '/s/$slug/$noteNumber/attachments/'
    | '/admin/spaces/$slug/fields/'
    | '/admin/spaces/$slug/filters/'
    | '/admin/spaces/$slug/fields/new'
    | '/admin/spaces/$slug/filters/new'
    | '/admin/spaces/$slug/fields/$fieldName/edit'
    | '/admin/spaces/$slug/filters/$filterName/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/s/$slug'
    | '/admin/pending-attachments'
    | '/admin/users'
    | '/s/$slug/new'
    | '/admin/spaces'
    | '/s/$slug/$noteNumber'
    | '/admin/spaces/import'
    | '/admin/spaces/new'
    | '/admin/telegram/mirrors'
    | '/admin/telegram/tasks'
    | '/admin/users/new'
    | '/s/$slug/$noteNumber/edit'
    | '/s/$slug/attachments/new'
    | '/s/$slug/attachments'
    | '/admin/spaces/$slug/export'
    | '/admin/spaces/$slug/members'
    | '/admin/spaces/$slug/settings'
    | '/admin/spaces/$slug/templates'
    | '/s/$slug/$noteNumber/attachments/new'
    | '/s/$slug/$noteNumber/attachments'
    | '/admin/spaces/$slug/fields'
    | '/admin/spaces/$slug/filters'
    | '/admin/spaces/$slug/fields/new'
    | '/admin/spaces/$slug/filters/new'
    | '/admin/spaces/$slug/fields/$fieldName/edit'
    | '/admin/spaces/$slug/filters/$filterName/edit'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/'
    | '/_auth/_admin'
    | '/_auth/s/$slug/'
    | '/_auth/_admin/admin/pending-attachments'
    | '/_auth/_admin/admin/users'
    | '/_auth/s/$slug/new'
    | '/_auth/_admin/admin/spaces/'
    | '/_auth/s/$slug/$noteNumber/'
    | '/_auth/_admin/admin/spaces/import'
    | '/_auth/_admin/admin/spaces/new'
    | '/_auth/_admin/admin/telegram/mirrors'
    | '/_auth/_admin/admin/telegram/tasks'
    | '/_auth/_admin/admin/users/new'
    | '/_auth/s/$slug/$noteNumber/edit'
    | '/_auth/s/$slug/attachments/new'
    | '/_auth/s/$slug/attachments/'
    | '/_auth/_admin/admin/spaces/$slug/export'
    | '/_auth/_admin/admin/spaces/$slug/members'
    | '/_auth/_admin/admin/spaces/$slug/settings'
    | '/_auth/_admin/admin/spaces/$slug/templates'
    | '/_auth/s/$slug/$noteNumber/attachments/new'
    | '/_auth/s/$slug/$noteNumber/attachments/'
    | '/_auth/_admin/admin/spaces/$slug/fields/'
    | '/_auth/_admin/admin/spaces/$slug/filters/'
    | '/_auth/_admin/admin/spaces/$slug/fields/new'
    | '/_auth/_admin/admin/spaces/$slug/filters/new'
    | '/_auth/_admin/admin/spaces/$slug/fields/$fieldName/edit'
    | '/_auth/_admin/admin/spaces/$slug/filters/$filterName/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authDotlayoutRoute: typeof authDotlayoutRouteWithChildren
  loginDotpageRoute: typeof loginDotpageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof loginDotpageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof authDotlayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_admin': {
      id: '/_auth/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof adminDotlayoutRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexPageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth/s/$slug/new': {
      id: '/_auth/s/$slug/new'
      path: '/s/$slug/new'
      fullPath: '/s/$slug/new'
      preLoaderRoute: typeof sSlugNewDotpageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth/_admin/admin/users': {
      id: '/_auth/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof adminUsersIndexPageRouteImport
      parentRoute: typeof adminDotlayoutRoute
    }
    '/_auth/_admin/admin/pending-attachments': {
      id: '/_auth/_admin/admin/pending-attachments'
      path: '/admin/pending-attachments'
      fullPath: '/admin/pending-attachments'
      preLoaderRoute: typeof adminPendingAttachmentsPageRouteImport
      parentRoute: typeof adminDotlayoutRoute
    }
    '/_auth/s/$slug/': {
      id: '/_auth/s/$slug/'
      path: '/s/$slug'
      fullPath: '/s/$slug/'
      preLoaderRoute: typeof sSlugIndexPageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth/s/$slug/attachments/': {
      id: '/_auth/s/$slug/attachments/'
      path: '/s/$slug/attachments'
      fullPath: '/s/$slug/attachments/'
      preLoaderRoute: typeof sSlugAttachmentsIndexDotpageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth/s/$slug/attachments/new': {
      id: '/_auth/s/$slug/attachments/new'
      path: '/s/$slug/attachments/new'
      fullPath: '/s/$slug/attachments/new'
      preLoaderRoute: typeof sSlugAttachmentsNewDotpageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth/s/$slug/$noteNumber/edit': {
      id: '/_auth/s/$slug/$noteNumber/edit'
      path: '/s/$slug/$noteNumber/edit'
      fullPath: '/s/$slug/$noteNumber/edit'
      preLoaderRoute: typeof sSlug_noteNumberEditPageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth/_admin/admin/users/new': {
      id: '/_auth/_admin/admin/users/new'
      path: '/admin/users/new'
      fullPath: '/admin/users/new'
      preLoaderRoute: typeof adminUsersNewDotpageRouteImport
      parentRoute: typeof adminDotlayoutRoute
    }
    '/_auth/_admin/admin/telegram/tasks': {
      id: '/_auth/_admin/admin/telegram/tasks'
      path: '/admin/telegram/tasks'
      fullPath: '/admin/telegram/tasks'
      preLoaderRoute: typeof adminTelegramTasksPageRouteImport
      parentRoute: typeof adminDotlayoutRoute
    }
    '/_auth/_admin/admin/telegram/mirrors': {
      id: '/_auth/_admin/admin/telegram/mirrors'
      path: '/admin/telegram/mirrors'
      fullPath: '/admin/telegram/mirrors'
      preLoaderRoute: typeof adminTelegramMirrorsPageRouteImport
      parentRoute: typeof adminDotlayoutRoute
    }
    '/_auth/_admin/admin/spaces/new': {
      id: '/_auth/_admin/admin/spaces/new'
      path: '/admin/spaces/new'
      fullPath: '/admin/spaces/new'
      preLoaderRoute: typeof adminSpacesNewDotpageRouteImport
      parentRoute: typeof adminDotlayoutRoute
    }
    '/_auth/_admin/admin/spaces/import': {
      id: '/_auth/_admin/admin/spaces/import'
      path: '/admin/spaces/import'
      fullPath: '/admin/spaces/import'
      preLoaderRoute: typeof adminSpacesImportDotpageRouteImport
      parentRoute: typeof adminDotlayoutRoute
    }
    '/_auth/s/$slug/$noteNumber/': {
      id: '/_auth/s/$slug/$noteNumber/'
      path: '/s/$slug/$noteNumber'
      fullPath: '/s/$slug/$noteNumber/'
      preLoaderRoute: typeof sSlug_noteNumberIndexPageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth/_admin/admin/spaces/': {
      id: '/_auth/_admin/admin/spaces/'
      path: '/admin/spaces'
      fullPath: '/admin/spaces/'
      preLoaderRoute: typeof adminSpacesIndexPageRouteImport
      parentRoute: typeof adminDotlayoutRoute
    }
    '/_auth/s/$slug/$noteNumber/attachments/': {
      id: '/_auth/s/$slug/$noteNumber/attachments/'
      path: '/s/$slug/$noteNumber/attachments'
      fullPath: '/s/$slug/$noteNumber/attachments/'
      preLoaderRoute: typeof sSlug_noteNumberAttachmentsIndexDotpageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth/s/$slug/$noteNumber/attachments/new': {
      id: '/_auth/s/$slug/$noteNumber/attachments/new'
      path: '/s/$slug/$noteNumber/attachments/new'
      fullPath: '/s/$slug/$noteNumber/attachments/new'
      preLoaderRoute: typeof sSlug_noteNumberAttachmentsNewDotpageRouteImport
      parentRoute: typeof authDotlayoutRoute
    }
    '/_auth/_admin/admin/spaces/$slug/templates': {
      id: '/_auth/_admin/admin/spaces/$slug/templates'
      path: '/admin/spaces/$slug/templates'
      fullPath: '/admin/spaces/$slug/templates'
      preLoaderRoute: typeof adminSpacesSlugTemplatesPageRouteImport
      parentRoute: typeof adminDotlayoutRoute
    }
    '/_auth/_admin/admin/spaces/$slug/settings': {
      id: '/_auth/_admin/admin/spaces/$slug/settings'
      path: '/admin/spaces/$slug/settings'
      fullPath: '/admin/spaces/$slug/settings'
      preLoaderRoute: typeof adminSpacesSlugSettingsPageRouteImport
      parentRoute: typeof adminDotlayoutRoute
    }
    '/_auth/_admin/admin/spaces/$slug/members': {
      id: '/_auth/_admin/admin/spaces/$slug/members'
      path: '/admin/spaces/$slug/members'
      fullPath: '/admin/spaces/$slug/members'
      preLoaderRoute: typeof adminSpacesSlugMembersDotpageRouteImport
      parentRoute: typeof adminDotlayoutRoute
    }
    '/_auth/_admin/admin/spaces/$slug/export': {
      id: '/_auth/_admin/admin/spaces/$slug/export'
      path: '/admin/spaces/$slug/export'
      fullPath: '/admin/spaces/$slug/export'
      preLoaderRoute: typeof adminSpacesSlugExportDotpageRouteImport
      parentRoute: typeof adminDotlayoutRoute
    }
    '/_auth/_admin/admin/spaces/$slug/filters/new': {
      id: '/_auth/_admin/admin/spaces/$slug/filters/new'
      path: '/admin/spaces/$slug/filters/new'
      fullPath: '/admin/spaces/$slug/filters/new'
      preLoaderRoute: typeof adminSpacesSlugFiltersNewDotpageRouteImport
      parentRoute: typeof adminDotlayoutRoute
    }
    '/_auth/_admin/admin/spaces/$slug/fields/new': {
      id: '/_auth/_admin/admin/spaces/$slug/fields/new'
      path: '/admin/spaces/$slug/fields/new'
      fullPath: '/admin/spaces/$slug/fields/new'
      preLoaderRoute: typeof adminSpacesSlugFieldsNewDotpageRouteImport
      parentRoute: typeof adminDotlayoutRoute
    }
    '/_auth/_admin/admin/spaces/$slug/filters/': {
      id: '/_auth/_admin/admin/spaces/$slug/filters/'
      path: '/admin/spaces/$slug/filters'
      fullPath: '/admin/spaces/$slug/filters/'
      preLoaderRoute: typeof adminSpacesSlugFiltersIndexPageRouteImport
      parentRoute: typeof adminDotlayoutRoute
    }
    '/_auth/_admin/admin/spaces/$slug/fields/': {
      id: '/_auth/_admin/admin/spaces/$slug/fields/'
      path: '/admin/spaces/$slug/fields'
      fullPath: '/admin/spaces/$slug/fields/'
      preLoaderRoute: typeof adminSpacesSlugFieldsIndexPageRouteImport
      parentRoute: typeof adminDotlayoutRoute
    }
    '/_auth/_admin/admin/spaces/$slug/filters/$filterName/edit': {
      id: '/_auth/_admin/admin/spaces/$slug/filters/$filterName/edit'
      path: '/admin/spaces/$slug/filters/$filterName/edit'
      fullPath: '/admin/spaces/$slug/filters/$filterName/edit'
      preLoaderRoute: typeof adminSpacesSlugFiltersFilterNameEditDotpageRouteImport
      parentRoute: typeof adminDotlayoutRoute
    }
    '/_auth/_admin/admin/spaces/$slug/fields/$fieldName/edit': {
      id: '/_auth/_admin/admin/spaces/$slug/fields/$fieldName/edit'
      path: '/admin/spaces/$slug/fields/$fieldName/edit'
      fullPath: '/admin/spaces/$slug/fields/$fieldName/edit'
      preLoaderRoute: typeof adminSpacesSlugFieldsFieldNameEditDotpageRouteImport
      parentRoute: typeof adminDotlayoutRoute
    }
  }
}

interface adminDotlayoutRouteChildren {
  adminPendingAttachmentsPageRoute: typeof adminPendingAttachmentsPageRoute
  adminUsersIndexPageRoute: typeof adminUsersIndexPageRoute
  adminSpacesIndexPageRoute: typeof adminSpacesIndexPageRoute
  adminSpacesImportDotpageRoute: typeof adminSpacesImportDotpageRoute
  adminSpacesNewDotpageRoute: typeof adminSpacesNewDotpageRoute
  adminTelegramMirrorsPageRoute: typeof adminTelegramMirrorsPageRoute
  adminTelegramTasksPageRoute: typeof adminTelegramTasksPageRoute
  adminUsersNewDotpageRoute: typeof adminUsersNewDotpageRoute
  adminSpacesSlugExportDotpageRoute: typeof adminSpacesSlugExportDotpageRoute
  adminSpacesSlugMembersDotpageRoute: typeof adminSpacesSlugMembersDotpageRoute
  adminSpacesSlugSettingsPageRoute: typeof adminSpacesSlugSettingsPageRoute
  adminSpacesSlugTemplatesPageRoute: typeof adminSpacesSlugTemplatesPageRoute
  adminSpacesSlugFieldsIndexPageRoute: typeof adminSpacesSlugFieldsIndexPageRoute
  adminSpacesSlugFiltersIndexPageRoute: typeof adminSpacesSlugFiltersIndexPageRoute
  adminSpacesSlugFieldsNewDotpageRoute: typeof adminSpacesSlugFieldsNewDotpageRoute
  adminSpacesSlugFiltersNewDotpageRoute: typeof adminSpacesSlugFiltersNewDotpageRoute
  adminSpacesSlugFieldsFieldNameEditDotpageRoute: typeof adminSpacesSlugFieldsFieldNameEditDotpageRoute
  adminSpacesSlugFiltersFilterNameEditDotpageRoute: typeof adminSpacesSlugFiltersFilterNameEditDotpageRoute
}

const adminDotlayoutRouteChildren: adminDotlayoutRouteChildren = {
  adminPendingAttachmentsPageRoute: adminPendingAttachmentsPageRoute,
  adminUsersIndexPageRoute: adminUsersIndexPageRoute,
  adminSpacesIndexPageRoute: adminSpacesIndexPageRoute,
  adminSpacesImportDotpageRoute: adminSpacesImportDotpageRoute,
  adminSpacesNewDotpageRoute: adminSpacesNewDotpageRoute,
  adminTelegramMirrorsPageRoute: adminTelegramMirrorsPageRoute,
  adminTelegramTasksPageRoute: adminTelegramTasksPageRoute,
  adminUsersNewDotpageRoute: adminUsersNewDotpageRoute,
  adminSpacesSlugExportDotpageRoute: adminSpacesSlugExportDotpageRoute,
  adminSpacesSlugMembersDotpageRoute: adminSpacesSlugMembersDotpageRoute,
  adminSpacesSlugSettingsPageRoute: adminSpacesSlugSettingsPageRoute,
  adminSpacesSlugTemplatesPageRoute: adminSpacesSlugTemplatesPageRoute,
  adminSpacesSlugFieldsIndexPageRoute: adminSpacesSlugFieldsIndexPageRoute,
  adminSpacesSlugFiltersIndexPageRoute: adminSpacesSlugFiltersIndexPageRoute,
  adminSpacesSlugFieldsNewDotpageRoute: adminSpacesSlugFieldsNewDotpageRoute,
  adminSpacesSlugFiltersNewDotpageRoute: adminSpacesSlugFiltersNewDotpageRoute,
  adminSpacesSlugFieldsFieldNameEditDotpageRoute:
    adminSpacesSlugFieldsFieldNameEditDotpageRoute,
  adminSpacesSlugFiltersFilterNameEditDotpageRoute:
    adminSpacesSlugFiltersFilterNameEditDotpageRoute,
}

const adminDotlayoutRouteWithChildren = adminDotlayoutRoute._addFileChildren(
  adminDotlayoutRouteChildren,
)

interface authDotlayoutRouteChildren {
  indexPageRoute: typeof indexPageRoute
  adminDotlayoutRoute: typeof adminDotlayoutRouteWithChildren
  sSlugIndexPageRoute: typeof sSlugIndexPageRoute
  sSlugNewDotpageRoute: typeof sSlugNewDotpageRoute
  sSlug_noteNumberIndexPageRoute: typeof sSlug_noteNumberIndexPageRoute
  sSlug_noteNumberEditPageRoute: typeof sSlug_noteNumberEditPageRoute
  sSlugAttachmentsNewDotpageRoute: typeof sSlugAttachmentsNewDotpageRoute
  sSlugAttachmentsIndexDotpageRoute: typeof sSlugAttachmentsIndexDotpageRoute
  sSlug_noteNumberAttachmentsNewDotpageRoute: typeof sSlug_noteNumberAttachmentsNewDotpageRoute
  sSlug_noteNumberAttachmentsIndexDotpageRoute: typeof sSlug_noteNumberAttachmentsIndexDotpageRoute
}

const authDotlayoutRouteChildren: authDotlayoutRouteChildren = {
  indexPageRoute: indexPageRoute,
  adminDotlayoutRoute: adminDotlayoutRouteWithChildren,
  sSlugIndexPageRoute: sSlugIndexPageRoute,
  sSlugNewDotpageRoute: sSlugNewDotpageRoute,
  sSlug_noteNumberIndexPageRoute: sSlug_noteNumberIndexPageRoute,
  sSlug_noteNumberEditPageRoute: sSlug_noteNumberEditPageRoute,
  sSlugAttachmentsNewDotpageRoute: sSlugAttachmentsNewDotpageRoute,
  sSlugAttachmentsIndexDotpageRoute: sSlugAttachmentsIndexDotpageRoute,
  sSlug_noteNumberAttachmentsNewDotpageRoute:
    sSlug_noteNumberAttachmentsNewDotpageRoute,
  sSlug_noteNumberAttachmentsIndexDotpageRoute:
    sSlug_noteNumberAttachmentsIndexDotpageRoute,
}

const authDotlayoutRouteWithChildren = authDotlayoutRoute._addFileChildren(
  authDotlayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authDotlayoutRoute: authDotlayoutRouteWithChildren,
  loginDotpageRoute: loginDotpageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
